### ISSUE TITLE
Tuning hyperparameters and priors for DirichletLM model

### ISSUE THREAD

**Issue by YaoM1886** [terrier-org/pyterrier#102]
Hi, I am currently having some trouble on tuning hyperparameters and priors for DirichletLM model. It seems apparent that the source code is wrapped in Java format but I could not find any clear documentation on how to tune these with Pyterrier. I found a closed issue#59 which was about setting parameters for BM25 model by "control" but no mention on other models. It will be much appreciated if there are more supportive documentations on custom modification of models. 

Especially for the prior part, I would like to extract some structural features such as document length, pagerank scores, keywords occurrence etc. Is there a convenient way to do so with the help of index? Thanks!

**Comment by cmacdonald** [comment]
Hi @YaoM1886 

Thanks for your question. We have already developed a gridsearch for PyTerrier in a separate branch. Hence why tuning of parameters are not yet well documented.  If you want a sneak preview of how it will work in the future, see https://github.com/terrier-org/pyterrier/blob/gridsearch/examples/notebooks/gridsearch.ipynb (in the gridsearch branch).

In the meanwhile, DirichletLM's mu parameter can be controlled using the "c" parameter also. Something like this should work:

```python
dfs=[]
br = pt.BatchRetrieve(index, wmodel="DirichletLM")
for mu in [500, 1000, 2000]:
  br.setControl("c", str(mu))
  df = pt.Experiment([br], topics, qrels, metrics, names=["Dirichlet mu=%d" % mu])
  dfs.append(df)
pd.concat(dfs)
```

Hope this helps.

**Comment by cmacdonald** [comment]
You also asked about priors - I'm assuming you refer to document priors. IIRC, in log space, these can be added to the score of DirichletLM.

In PyTerrier:
```python
from pyterrier.transformer import IdentityTransformer
br = pt.BatchRetrieve(index)
#one for each document
prior=np.ones(index.getCollectionStatistics().getNumberOfDocuments())
alpha=0.5
with_priors = br >> (IdentityTransformer() + alpha * pt.apply.doc_score(lambda row: prior[row.docid]))
```

HTH

**Comment by YaoM1886** [comment]
Thanks for your detailed answers. This really helps! 
According to your code, if I may ask, from which documentation can I find the list properties of index, such as all the methods of index.getCollectionStatistics()?

**Comment by cmacdonald** [comment]
Terrier (which is the underlying engine) has javadoc available at http://terrier.org/docs/current/javadoc/
In particular, see http://terrier.org/docs/current/javadoc/org/terrier/structures/Index.html
http://terrier.org/docs/current/javadoc/org/terrier/structures/CollectionStatistics.html

PyTerrier has an index API notebook showing some examples:
https://github.com/terrier-org/pyterrier/blob/master/examples/notebooks/index_api.ipynb

Some Java types are patched, so that they are easier to use in Python. For example, an IterablePosting object can be iterated using `for` loop in Python, Lexicon responds to `len()`, `in` etc

**Comment by YaoM1886** [comment]
All clear:)Thank you!

**Comment by YaoM1886** [comment]
All clear:)Thank you!
