### ISSUE TITLE
Tokenising/escaping queries

### ISSUE THREAD

**Issue by seanmacavaney** [terrier-org/pyterrier#104]
RemoteDataset tokenises the input queries, so they do not conflict with the Terrier query language. IrdsDataset doesn't. This can cause errors when retrieving. An easy solution would be to feed IrdsDataset through the terrier tokeniser.

We may also want a transformer that does this. Such a transformer would help people work with their own collections.

**Comment by cmacdonald** [comment]
Something like:
```
query = "hello"
tokeniser = pt.autoclass("org.terrier.indexing.tokenisation.Tokeniser").getTokeniser()
tokenised = ' '.join(tokeniser.getTokens(query))
```

I note that `getTokens()` is overloaded on the Java side. That might make things tricky from PyTerrier. Let me know if that happens. Making a Java string first might get around the problem.
