### ISSUE TITLE
SequentialDependence returned error

### ISSUE THREAD

**Issue by TimMo-prog** [terrier-org/pyterrier#105]
Hi, I am trying to use SequentialDependence to rewrite the queries from MSMARCO Document dataset by following the example in the 

> https://pyterrier.readthedocs.io/en/latest/rewrite.html

However, the I got the error like this: 

`12:43:20.127 [main] ERROR org.terrier.querying.LocalManager - Problem running Matching, returning empty result set as query 532603
java.io.IOException: This index does not support blocks
	at org.terrier.matching.matchops.PhraseOp.createFinalPostingIterator(PhraseOp.java:85) ~[terrier-assemblies-5.4-jar-with-dependencies.jar:na]
	at org.terrier.matching.matchops.MultiTermOp.getPostingIterator(MultiTermOp.java:131) ~[terrier-assemblies-5.4-jar-with-dependencies.jar:na]
	at org.terrier.matching.matchops.MultiTermOp.getMatcher(MultiTermOp.java:147) ~[terrier-assemblies-5.4-jar-with-dependencies.jar:na]
	at org.terrier.matching.PostingListManager.<init>(PostingListManager.java:304) ~[terrier-assemblies-5.4-jar-with-dependencies.jar:na]
	at org.terrier.matching.PostingListManager.<init>(PostingListManager.java:282) ~[terrier-assemblies-5.4-jar-with-dependencies.jar:na]
	at org.terrier.matching.daat.Full.match(Full.java:82) ~[terrier-assemblies-5.4-jar-with-dependencies.jar:na]
	at org.terrier.querying.LocalManager$ApplyLocalMatching.process(LocalManager.java:522) ~[terrier-assemblies-5.4-jar-with-dependencies.jar:na]
	at org.terrier.querying.LocalManager.runSearchRequest(LocalManager.java:916) ~[terrier-assemblies-5.4-jar-with-dependencies.jar:na]
Caused by: java.lang.ClassCastException: class org.terrier.structures.postings.bit.BasicIterablePosting cannot be cast to class org.terrier.structures.postings.BlockPosting (org.terrier.structures.postings.bit.BasicIterablePosting and org.terrier.structures.postings.BlockPosting are in unnamed module of loader 'app')
	at org.terrier.structures.postings.PhraseIterablePosting.<init>(PhraseIterablePosting.java:58) ~[terrier-assemblies-5.4-jar-with-dependencies.jar:na]
	at org.terrier.matching.matchops.PhraseOp.createFinalPostingIterator(PhraseOp.java:83) ~[terrier-assemblies-5.4-jar-with-dependencies.jar:na]
	... 7 common frames omitted`

I am able to run Bo1QueryExpansion and KLQueryExpansion with no errors. I would like to know how can I fix the issue above?

Here is the code I use:

`sdm = pt.rewrite.SequentialDependence()
dph = pt.BatchRetrieve(index, wmodel="DirichletLM", properties={"termpipelines": ""}, verbose=True) % 100
DirichletLM_br = sdm >> dph
pt.Experiment([DirichletLM_br], dataset.get_topics("test"), dataset.get_qrels("test"), eval_metrics=["recip_rank"])`

**Comment by cmacdonald** [comment]
Hi,

You need to reindex with blocks=True - see https://pyterrier.readthedocs.io/en/latest/terrier-indexing.html

Indexing doesnt record "position" information by default, as it makes the indices much larger and also slower.

Craig
________________________________

**Comment by cmacdonald** [comment]
I’ll update the documentation for SDM to reflect that.

Craig

Sent from my iPhone

On 4 Mar 2021, at 14:49, Craig Macdonald <Craig.Macdonald@glasgow.ac.uk> wrote:

﻿
Hi,

You need to reindex with blocks=True - see https://pyterrier.readthedocs.io/en/latest/terrier-indexing.html

Indexing doesnt record "position" information by default, as it makes the indices much larger and also slower.

Craig
________________________________

**Comment by TimMo-prog** [comment]
Hi Craig, it worked after specifying 'blocks=True' in the code. Thanks!

**Comment by TimMo-prog** [comment]
Hi Craig, I got an JVM exception after deploying the SequentialDependence into the code while using the 
MS MARCO dev dataset on Google Colab.

I also tried to add commands from 

> https://github.com/terrier-org/pyterrier/issues/62:

```
!apt-get install maven
!git clone https://github.com/terrier-org/terrier-core.git && cd terrier-core && mvn -DskipTests clean install
```

, but I still got the same JavaException. However, I can get the evaluation result of dev dataset when I did not use SequentialDependence. In addition, there is no issue while evaluating on MS MARCO test dataset with SequentialDependence. I would like to know how I can fix this issue in this case.


```
Downloading trec-deep-learning-docs topics to /root/.pyterrier/corpora/trec-deep-learning-docs/msmarco-docdev-queries.tsv.gz
msmarco-docdev-queries.tsv.gz: 100%|██████████| 89.7k/89.7k [00:00<00:00, 510kiB/s]
Downloading trec-deep-learning-docs qrels to /root/.pyterrier/corpora/trec-deep-learning-docs/msmarco-docdev-qrels.tsv.gz
msmarco-docdev-qrels.tsv.gz: 100%|██████████| 37.6k/37.6k [00:00<00:00, 536kiB/s]
BR(DirichletLM):  83%|████████▎ | 4303/5193 [58:26<09:58,  1.49q/s]
---------------------------------------------------------------------------
JavaException                             Traceback (most recent call last)
<ipython-input-12-8e81ec12f6d3> in <module>()
      7 # start_evaluation_time = time.time()
----> 8 pt.Experiment([DirichletLM_br], dataset.get_topics("dev"), dataset.get_qrels("dev"), eval_metrics=["recip_rank"])
      9 # print("evaluation time: ")
     10 # print(time.time() - start_evaluation_time)

3 frames
/usr/local/lib/python3.7/dist-packages/pyterrier/pipelines.py in Experiment(retr_systems, topics, qrels, eval_metrics, names, perquery, dataframe, baseline, highlight, round)
    131         else:
    132             starttime = timer()
--> 133             results.append(system.transform(topics))
    134             endtime = timer()
    135             times.append( (endtime - starttime) * 1000.)

/usr/local/lib/python3.7/dist-packages/pyterrier/transformer.py in transform(self, topics)
    740     def transform(self, topics):
    741         for m in self.models:
--> 742             topics = m.transform(topics)
    743         return topics
    744 

/usr/local/lib/python3.7/dist-packages/pyterrier/transformer.py in transform(self, topics_and_res)
    468 
    469     def transform(self, topics_and_res):
--> 470         res = self.transformer.transform(topics_and_res)
    471         if not "rank" in res.columns:
    472             assert False, "require rank to be present in the result set"

/usr/local/lib/python3.7/dist-packages/pyterrier/batchretrieve.py in transform(self, queries)
    198 
    199             # now ask Terrier to run the request
--> 200             self.manager.runSearchRequest(srq)
    201             result = srq.getResults()
    202 

jnius/jnius_export_class.pxi in jnius.JavaMethod.__call__()

jnius/jnius_export_class.pxi in jnius.JavaMethod.call_method()

jnius/jnius_jvm_dlopen.pxi in jnius.create_jnienv()

JavaException: JVM exception occurred: Failed to process '' org.terrier.querying.parser.QueryParserException`


```

Here is the code I use:
```
!rm -rf index/
!mkdir -p index
props = {
  'indexer.meta.reverse.keys':'docno',
  'termpipelines' : '',
}
pt.logging('INFO')
indexer = pt.TRECCollectionIndexer("./index", blocks=True)
indexer.setProperties(**props)
indexref = indexer.index(dataset.get_corpus())
pt.logging('WARN')
index = pt.IndexFactory.of(indexref)

sdm = pt.rewrite.SequentialDependence()
dph = pt.BatchRetrieve(index, wmodel="DirichletLM", properties={"termpipelines": ""}, verbose=True) % 100
DirichletLM_br = sdm >> dph

pt.Experiment([DirichletLM_br], dataset.get_topics("dev"), dataset.get_qrels("dev"), eval_metrics=["recip_rank"])

```

**Comment by cmacdonald** [comment]
I gave a look at this. It seems sdm creates an empty query for qid 975997:

<img width="427" alt="image" src="https://user-images.githubusercontent.com/620938/110213393-bebab280-7e97-11eb-9969-d510824ed3fb.png">

The original query was:

<img width="311" alt="image" src="https://user-images.githubusercontent.com/620938/110213431-e3af2580-7e97-11eb-8f91-9cb798d8020e.png">

Setting the `remove_stopwords=False` constructor kwarg to SDM makes the problem go away.

BatchRetrieve should probably catch if the query is empty and bypass it while omitting a warning. I'll make an issue so this is addressed for the next release.
