### ISSUE TITLE
An JVM exception on Learning to Rank

### ISSUE THREAD

**Issue by TimMo-prog** [terrier-org/pyterrier#112]
Hi Craig, I tried to use the features mentioned in the Terrier documentation for the Learning to Rank on MS MARCO Document ranking dataset. 

> https://github.com/terrier-org/terrier-core/blob/5.x/doc/learning.md

But I got an JVM exception:

```
No etc/terrier.properties, using terrier.default.properties for bootstrap configuration.
FBR(DirichletLM and 6 features):   0%|          | 0/367013 [00:03<?, ?q/s]
Traceback (most recent call last):
  File "/Volumes/Nieuw/LTR/sample_LTR.py", line 23, in <module>
    rf_pipe.fit(dataset.get_topics("train"), dataset.get_qrels("train"))
  File "/Users/tianyumo/.conda/envs/LTR/lib/python3.6/site-packages/pyterrier/transformer.py", line 755, in fit
    topics_or_res_tr = m.transform(topics_or_res_tr)
  File "/Users/tianyumo/.conda/envs/LTR/lib/python3.6/site-packages/pyterrier/batchretrieve.py", line 479, in transform
    self.manager.runSearchRequest(srq)
  File "jnius/jnius_export_class.pxi", line 857, in jnius.JavaMethod.__call__
  File "jnius/jnius_export_class.pxi", line 954, in jnius.JavaMethod.call_method
  File "jnius/jnius_jvm_dlopen.pxi", line 91, in jnius.create_jnienv
jnius.JavaException: JVM exception occurred: class org.terrier.structures.BasicLexiconEntry cannot be cast to class org.terrier.structures.FieldEntryStatistics (org.terrier.structures.BasicLexiconEntry and org.terrier.structures.FieldEntryStatistics are in unnamed module of loader 'app') java.lang.ClassCastException

```
 I also tried to use these features on the Learning to Rank Examples.ipynb 

> https://colab.research.google.com/github/terrier-org/pyterrier/blob/master/examples/notebooks/ltr.ipynbby

by replacing `fbr = pt.FeaturesBatchRetrieve(indexref, controls = {"wmodel": "BM25"}, features=["WMODEL:TF_IDF", "WMODEL:PL2"])`  
with 
`fbr = pt.FeaturesBatchRetrieve(indexref, controls = {"wmodel": "BM25"}, features=["WMODEL:SingleFieldModel(BM25,0)", "WMODEL:SingleFieldModel(BM25,1)", "QI:SingleFieldModel(Dl,0)", "QI:SingleFieldModel(Dl,1)", "DSM:org.terrier.matching.dsms.DFRDependenceScoreModifier", "DSM:org.terrier.matching.dsms.MRFDependenceScoreModifier"])` but I got the same exception. I would like to know whether you have any suggestions for fixing this exception?

Here is my code below:

```

pipeline = pt.FeaturesBatchRetrieve(index,
                                    wmodel="DirichletLM",
                                    properties={"termpipelines": ""},
                                    verbose=True,
                                    features=["WMODEL:SingleFieldModel(BM25,0)", "WMODEL:SingleFieldModel(BM25,1)", "QI:SingleFieldModel(Dl,0)", "QI:SingleFieldModel(Dl,1)", "DSM:org.terrier.matching.dsms.DFRDependenceScoreModifier", "DSM:org.terrier.matching.dsms.MRFDependenceScoreModifier"])
dataset = pt.get_dataset("trec-deep-learning-docs")
rf = RandomForestRegressor(n_estimators=100, max_depth=20)
rf_pipe = pipeline >> pt.ltr.apply_learned_model(rf)
rf_pipe.fit(dataset.get_topics("train"), dataset.get_qrels("train"))
LTR_test = pt.Experiment([rf_pipe], dataset.get_topics("test"), dataset.get_qrels("test"), ["recip_rank"], names=["LTR"])
```

**Comment by cmacdonald** [comment]
Hi,

Firstly, can I ask if you saw my reply on https://github.com/terrier-org/pyterrier/issues/105#issuecomment-791982328?

Using SingleFieldModel (or PL2F), you will need to index with fields (as well as blocks). I dont at time of writing have an example for indexing MSMARCO using fields.  Part of the problem IIRC is that MSMARCO doesnt properly separate URL from the text of the document - we had to regenerate a version of the corpus.

There are suggestions about field indexing configuration at https://pyterrier.readthedocs.io/en/latest/terrier-indexing.html

Craig

**Comment by cmacdonald** [comment]
Ps: trying to fit an LTR model on ALL training topics for MSMARCO will not end well. Start small, increase scale once you have something working.

Our TREC notebook papers suggested 500 training topics IIRC.

**Comment by TimMo-prog** [comment]
Thank you for your suggestions, I will get started with a small training topics in this case. And I think I already read your comments for the #105. Since MS MARCO is much larger. I just tried to add 'blocks=True' into the code from 'Learning to Rank Examples.ipynb'. But I still got that exception.

```
16:10:23.636 [main] INFO  org.terrier.querying.LocalManager - Starting to execute query 1 - measurement of dielectric constant of liquids by the use of microwave techniques
16:10:23.663 [main] INFO  org.terrier.querying.LocalManager - running process TerrierQLParser
16:10:23.689 [main] INFO  org.terrier.querying.LocalManager - running process TerrierQLToControls
16:10:23.703 [main] INFO  org.terrier.querying.LocalManager - running process TerrierQLToMatchingQueryTerms
16:10:23.722 [main] INFO  org.terrier.querying.LocalManager - running process ApplyTermPipeline(termpipelines=Stopwords,PorterStemmer)
16:10:23.735 [main] INFO  org.terrier.querying.LocalManager - running process ApplyLocalMatching
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecatedWarning: LTR_pipeline is deprecated as of 0.3.0. Please use pt.ltr.apply_learned_model(learner, form='regression')
  This is separate from the ipykernel package so we can avoid doing imports until
16:10:23.814 [main] INFO  org.terrier.querying.LocalManager - measur { req=null, w=1.0, stats=null, models=[org.terrier.matching.models.BM25@4d5650ae] tags=[firstmatchscore]} dielectr { req=null, w=1.0, stats=null, models=[org.terrier.matching.models.BM25@750e2b97] tags=[firstmatchscore]} constant { req=null, w=1.0, stats=null, models=[org.terrier.matching.models.BM25@3e27aa33] tags=[firstmatchscore]} liquid { req=null, w=1.0, stats=null, models=[org.terrier.matching.models.BM25@2e385cce] tags=[firstmatchscore]} microwav { req=null, w=1.0, stats=null, models=[org.terrier.matching.models.BM25@2ddc9a9f] tags=[firstmatchscore]} techniqu { req=null, w=1.0, stats=null, models=[org.terrier.matching.models.BM25@298a5e20] tags=[firstmatchscore]} 
16:10:23.904 [main] INFO  o.t.matching.PostingListManager - Query 1 with 6 terms has 2 posting lists
16:10:23.979 [main] INFO  org.terrier.matching.Matching - term constant ks=1.0 es=term663 Nt=368 TF=436 maxTF=4 @{0 212407 1} tag=[firstmatchscore]
16:10:23.995 [main] INFO  org.terrier.matching.Matching - term liquid ks=1.0 es=term375 Nt=38 TF=45 maxTF=2 @{0 523941 0} tag=[firstmatchscore]
16:10:24.020 [main] INFO  o.t.matching.FatScoringMatching - Using all terms from fat result set for scoring
---------------------------------------------------------------------------
JavaException                             Traceback (most recent call last)
<ipython-input-11-a19fb7741b0e> in <module>()
      2 
      3 BaselineLTR = fbr >> pt.pipelines.LTR_pipeline(RandomForestRegressor(n_estimators=400))
----> 4 BaselineLTR.fit(train_topics, qrels)
      5 
      6 results = pt.pipelines.Experiment([PL2, BaselineLTR], test_topics, qrels, ["map"], names=["PL2 Baseline", "LTR Baseline"])

1 frames
/usr/local/lib/python3.7/dist-packages/pyterrier/batchretrieve.py in transform(self, queries)
    477                 srq.setControl("matching", ",".join(["FatFeaturedScoringMatching","ScoringMatchingWithFat", srq.getControl("matching")]))
    478 
--> 479             self.manager.runSearchRequest(srq)
    480             srq = cast('org.terrier.querying.Request', srq)
    481             fres = cast('org.terrier.learning.FeaturedResultSet', srq.getResultSet())

jnius/jnius_export_class.pxi in jnius.JavaMethod.__call__()

jnius/jnius_export_class.pxi in jnius.JavaMethod.call_method()

jnius/jnius_jvm_dlopen.pxi in jnius.create_jnienv()

JavaException: JVM exception occurred: class org.terrier.structures.BasicLexiconEntry cannot be cast to class org.terrier.structures.FieldEntryStatistics (org.terrier.structures.BasicLexiconEntry and org.terrier.structures.FieldEntryStatistics are in unnamed module of loader 'app') java.lang.ClassCastException
```

I assume I still miss something in this case. Could you tell me what I can do further? I only found the information about field in the pyterrier.DFIndexer section.

Thank you in advance!

The code I used:

```
dataset = pt.datasets.get_dataset("vaswani")
!rm -rf index/
!mkdir -p index
props = {
  'indexer.meta.reverse.keys':'docno',
  'termpipelines' : '',
}
pt.logging('INFO')
indexer = pt.TRECCollectionIndexer("./index", blocks=True)
indexer.setProperties(**props)
indexref = indexer.index(dataset.get_corpus())
topics = dataset.get_topics()
qrels = dataset.get_qrels()

fbr = pt.FeaturesBatchRetrieve(indexref, controls = {"wmodel": "BM25"}, features=["WMODEL:SingleFieldModel(BM25,0)", "WMODEL:SingleFieldModel(BM25,1)", "QI:SingleFieldModel(Dl,0)", "QI:SingleFieldModel(Dl,1)", "DSM:org.terrier.matching.dsms.DFRDependenceScoreModifier", "DSM:org.terrier.matching.dsms.MRFDependenceScoreModifier"])
pipe = BM25 >> (pt.transformer.IdentityTransformer() ** TF_IDF ** PL2)

from sklearn.ensemble import RandomForestRegressor
BaselineLTR = fbr >> pt.pipelines.LTR_pipeline(RandomForestRegressor(n_estimators=400))
BaselineLTR.fit(train_topics, qrels)
results = pt.pipelines.Experiment([PL2, BaselineLTR], test_topics, qrels, ["map"], names=["PL2 Baseline", "LTR Baseline"])
results 
```

**Comment by cmacdonald** [comment]
As I said above, SingleFieldModel needs an index with fields NOT JUST blocks. Using a well-formatted TREC corpus **with tags** the configuration would be as detailed in
https://github.com/terrier-org/terrier-core/blob/5.x/doc/configure_indexing.md#fields

MSMARCO-docs.trec.gz is not well formatted. Hence indexing with fields is more involved. You could reformat MSMARCO-docs.tsv.gz into TREC-like format, or index MSMARCO-docs.tsv.gz directly using IterDictIndexer, specifying the fields. 

HTH

**Comment by TimMo-prog** [comment]
Hi Craig, thank you for your help. There is no that JVM exception anymore while using vaswani dataset after following the configure_indexing.md instruction you provided. I going to follow your suggestion to fix the issue in MSMARCO-docs.

By the way, I found an issue in the current version of "Learning to Rank Examples.ipynb": 

```
/usr/local/lib/python3.7/dist-packages/pyterrier/transformer.py:470: FutureWarning: .transform() should be passed a dataframe. Use .search() to execute a single query.
  res = self.transformer.transform(topics_and_res)
Applying 8 rules
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-1bc92e7ea800> in <module>()
      1 pipe_fast = pipe.compile()
----> 2 (pipe_fast %2).transform("chemical")

1 frames
/usr/local/lib/python3.7/dist-packages/pyterrier/batchretrieve.py in transform(self, queries)
    430             if self.wmodel is None:
    431                 raise ValueError("We're in retrieval mode (input columns were "+str(queries.columns)+"), but wmodel is None. FeaturesBatchRetrieve requires a wmodel be set for identifying the candidate set. "
--> 432                     +" Hint: wmodel argument for FeaturesBatchRetrieve, e.g. FeaturesBatchRetrieve(index, features, wmodel=\"DPH\")")
    433 
    434         if queries["qid"].dtype == np.int64:

ValueError: We're in retrieval mode (input columns were Index(['qid', 'query'], dtype='object')), but wmodel is None. FeaturesBatchRetrieve requires a wmodel be set for identifying the candidate set.  Hint: wmodel argument for FeaturesBatchRetrieve, e.g. FeaturesBatchRetrieve(index, features, wmodel="DPH") 
```

> As I said above, SingleFieldModel needs an index with fields NOT JUST blocks. Using a well-formatted TREC corpus **with tags** the configuration would be as detailed in
> https://github.com/terrier-org/terrier-core/blob/5.x/doc/configure_indexing.md#fields
> 
> MSMARCO-docs.trec.gz is not well formatted. Hence indexing with fields is more involved. You could reformat MSMARCO-docs.tsv.gz into TREC-like format, or index MSMARCO-docs.tsv.gz directly using IterDictIndexer, specifying the fields.
> 
> HTH

**Comment by cmacdonald** [comment]
Thanks for the headsup on the ltr.ipynb. I have committed fixes for this. :-)

**Comment by TimMo-prog** [comment]
Hi Craig, I already indexed the msmarco-docs.tsv by using IterDictIndexer successfully on Colab. And then the program asked me to set the index.meta.data-source: 

`22:23:28.858 [main] WARN  o.t.structures.CompressingMetaIndex - Structure meta reading data file directly from disk (SLOW) - try index.meta.data-source=fileinmem in the index properties file. 4.4 GiB of memory would be required.`

I set the index.meta.data-source as fileinmem in data.properties. But I got another info soon:

`22:07:26.827 [main] WARN  o.t.structures.CompressingMetaIndex - OutOfMemoryError: Structure meta reading data file directly from disk`

Do you have any suggestions to fix this issue? The learning process was quite slow with "index.meta.data-source=file", which took about 60 seconds per p.

**Comment by cmacdonald** [comment]
Its a warning. Things should work fine without that.  You can give the JVM more memory by setting the `mem` flag in `pt.init()`, e.g. `pt.init(mem=20000)`

What is "60 seconds per p."?

**Comment by TimMo-prog** [comment]
> Its a warning. Things should work fine without that. You can give the JVM more memory by setting the `mem` flag in `pt.init()`, e.g. `pt.init(mem=20000)`
> 
> What is "60 seconds per p."?

Oh, sorry, that is a typo. Console showed me "42.61s/q".

![Screenshot 2021-03-09 at 23 28 20](https://user-images.githubusercontent.com/70914112/110547127-c8f6de00-812f-11eb-914d-fd62587fdbf2.png)

**Comment by cmacdonald** [comment]
Perhaps use less documents per query. Set `num_results=100` in pt.BatchRetrieve().

**Comment by TimMo-prog** [comment]
> Perhaps use less documents per query. Set `num_results=100` in pt.BatchRetrieve().
> 
> Can you also check one thing for me in your new data.properties file:
> `index.document.class=org.terrier.structures.FSAFieldDocumentIndex`
> 
> Did you index lots of metadata this time? The more you index, the slower retrieval is, even if you dont use it.

I tried to add "mem=20000" and "num_results=100". The speed was improved but still a little bit slow:
![Screenshot 2021-03-10 at 00 05 40](https://user-images.githubusercontent.com/70914112/110550643-6227f380-8134-11eb-99dd-14f20c7dae65.png)

Here is the part of data.properties:

![Screenshot 2021-03-10 at 00 07 17](https://user-images.githubusercontent.com/70914112/110550791-9d2a2700-8134-11eb-9c62-7c54f3e238c4.png)

I think the "lots of metadata" is the main reason why it is so slow. 

I would like to know how I should set the meta and meta_lengths properly when I need the fields for the four parts?  

Here is the code I used for indexing:

`indexref = indexer.index(msmarco_generate(), fields=['docno', 'url', 'title', 'text'], meta=['docno', 'url', 'title', 'text'], meta_lengths=[20, 512, 512, 4096])`

**Comment by cmacdonald** [comment]
Change it to this:
`index.document.class=org.terrier.structures.FSAFieldDocumentIndex`
Things will be faster! Documented at https://github.com/terrier-org/terrier-core/blob/5.x/doc/configure_retrieval.md#field-based-weighting-models
I need to check why this is still happening - I thought I had resolved in https://github.com/terrier-org/terrier-core/issues/93

**Comment by TimMo-prog** [comment]
Hi Craig, seem like there is a significant speed improvement after using `index.document.class=org.terrier.structures.FSAFieldDocumentIndex` 


![Screenshot 2021-03-10 at 16 01 13](https://user-images.githubusercontent.com/70914112/110650114-8b8b6280-81ba-11eb-9e7a-1c7ac744bba6.png)

Thanks for you help!

PS. I am not going to train 367013 queries once, just for testing :P

**Comment by cmacdonald** [comment]
Excellent! I will reopen https://github.com/terrier-org/terrier-core/issues/93 to address the issue longer term.
