### ISSUE TITLE
pt.apply operations for making a new column and dropping a column

### ISSUE THREAD

**Issue by cmacdonald** [terrier-org/pyterrier#121]
Suggestions are:

Drop:
```python
pt.apply.drop(colname : str)
```
Make:
```python
pt.apply.make(colname : str, callable)
```

Example:

```python
foo >> pt.apply.make("text", lambda row : row["text"] + ' ' + row["querygen"] ) >> pt.apply.drop("querygen") >> bar
```

Nomenclature discussion:
 - it is right that these are pt.apply - I think so. At least make() takes a callable such as a lambda
 - are the named right? 
 - is it clear that make() works at a row level, rather than getting one query group or the entire df at a time.

**Comment by cmacdonald** [comment]
Add rename too?

**Comment by cmacdonald** [comment]
@seanmacavaney any comments?

**Comment by seanmacavaney** [comment]
How about `pt.apply.<any_column>(callable)`? This mimics the `pt.apply.query` now. I think it may read a bit better?

```python
pt.apply.text(lambda row: row["text"] + ' ' + row["querygen"])
pt.apply.query(lambda row: whatever)
...
```

Drop could be handled with `pt.apply.<any_column>(drop=True)`

This approach would involve a bit of re-working, but should be doable with `__getattr__`

**Comment by cmacdonald** [comment]
very smart! Think I understand how this can be implemented

**Comment by cmacdonald** [comment]
Merged. We can revisit structuring of methods in future.
