### ISSUE TITLE
How to open an index for retrieval

### ISSUE THREAD

**Issue by stamatisvas** [terrier-org/pyterrier#125]
How can I read my index using colab? All the documentation refers to the pre-built index of the 'vaswani' dataset i.e. vaswani_dataset = pt.datasets.get_dataset("vaswani")
indexref = vaswani_dataset.get_index()
index = pt.IndexFactory.of(indexref)

If I want to retrieve from my own index created using local documents, how can I import this index in my environment and run queries from colab?

**Comment by cmacdonald** [comment]
Hi @stamatisvas.

Thanks for your question.  There are examples of creating indices in https://pyterrier.readthedocs.io/en/latest/terrier-indexing.html - for instance, a dataframe of your own documents can be indexed using DFIndexer, as TREC collection using TRECCollectionIndexer.

An indexer usually returns an indexref, which you can use in pt.BatchRetrieve() directly, or instantiate as an index (see https://pyterrier.readthedocs.io/en/latest/terrier-retrieval.html#index-like-objects).

To help us improve the documentation, which particular example did you find the vaswani code, and where could we have inserted such a hint?

**Comment by stamatisvas** [comment]
Thanks for the answer. My issue solved. To avoid similar confusion with mine I would suggest instead of a prebuilt index use a small sample of docs to explain everything. But most importantly as the file data.properties exist in all indexes created by terrier change the "/path/to/data.properties" and ask the user to provide just the path of the index i.e. "/path/to/index" to be consistent with other tools i.e. anserini. This caused the main misunderstanding. Thanks!

**Comment by cmacdonald** [comment]
I've been down the file vs. (path, prefix) discussion before. I prefer "/path/to/data.properties" as its definite, and points to an actual file.

We'll check over documentation for other places. But purpose of pre-built index is to ensure that a full experiment can be conducted.

**Comment by cmacdonald** [comment]
>I've been down the file vs. (path, prefix) discussion before. I prefer "/path/to/data.properties" as its definite, and points to an actual file.

But we can check for a directory that contains data.properties.

**Comment by cmacdonald** [comment]
Hi @stamatisvas, thanks for the feedback. I have resolved terrier-org/terrier-core#154 which addresses your feedback!
