### ISSUE TITLE
If local corpus isnt found, corpus_iter should fail for IRDS

### ISSUE THREAD

**Issue by Xiao0728** [terrier-org/pyterrier#127]
Hi, 
I was trying to load "Robust04" dataset, but got this:
![image](https://user-images.githubusercontent.com/43675140/112980561-f09afe00-9151-11eb-978c-add5d9cb69e3.png)
Does it indicate that no documents were loaded there? @seanmacavaney Thanks.
Xiao

**Comment by seanmacavaney** [comment]
Good find-- thanks. IRDS is a little bullish on non-downloadable datasets, and I'll find a way to better verify that they are provided correctly (as well as improve the documentation on what to link). @Xiao0728, can you provide suggestions on what to improve in the message describing how to link?

**Comment by cmacdonald** [comment]
Ok, so addressed upstream. Once we test here, we can close.
