### ISSUE TITLE
cannot load and use RM3

### ISSUE THREAD

**Issue by DayalStrub** [terrier-org/pyterrier#131]
The suggested import of pyterrier with terrier-prf, as mentioned in docs and [warning](https://github.com/terrier-org/pyterrier/blob/8a902ebf824a11c9b260a1ea4fa61a95c617d20e/pyterrier/rewrite.py#L254) doesn't seem to work.

I'm simply running 

```python
import pyterrier as pt
pt.init(boot_packages=["org.terrier:terrier-prf:0.0.1-SNAPSHOT"])
```
after having installed pyterrier in a colab notebook (following examples from workshop).

I don't use Java, so not sure what to look for, but indeed can't see terrier-prf in [maven repo](https://repo1.maven.org/maven2/org/terrier/).

**Comment by cmacdonald** [comment]
Thanks @DayalStrub. 

This should work:
```python
import pyterrier as pt
pt.init(boot_packages=["com.github.terrierteam:terrier-prf:-SNAPSHOT"])
```
(this uses [Jitpack](https://jitpack.io/) to build a jar file from Github)

The rest of a working example I just tried is:
```python
dataset = pt.get_dataset("vaswani")
index = dataset.get_index()
bm25 = pt.BatchRetrieve(index, wmodel="BM25")
rm3_pipe = bm25 >> pt.rewrite.RM3(index) >> bm25
pt.Experiment([bm25, rm3_pipe],
              dataset.get_topics(),
              dataset.get_qrels(),
              ["map"]
              )
```

I'll patch PyTerrier to fix this.

**Comment by cmacdonald** [comment]
Improved documentation - thanks for the headsup @DayalStrub 
https://pyterrier.readthedocs.io/en/latest/rewrite.html#rm3

Is there a name and affiliation I can note in the change log?

**Comment by DayalStrub** [comment]
@cmacdonald just tried and indeed it works now. thanks for the quick fix/reply!

as you were the one fixing, no need for any mention. i think the project/idea is very nice so if (or hopefully when) i make a PR, then i can appear in the change log.

going to close this now, assuming there isn't anything else you wanted to do/commit.
