### ISSUE TITLE
more pre-built indices?

### ISSUE THREAD

**Issue by cmacdonald** [terrier-org/pyterrier#136]

**Comment by cmacdonald** [comment]
Q: Where to host?

Q: If they are mainly for BatchRetrieve, should BatchRetrieve have a static method to instantiate from a specified dataset?

```python

class BatchRetrieve:
    @staticmethod
    def from_dataset(dataset : Union[Dataset,str], variant : str = None):
        pass


br = pt.BatchRetrieve.from_dataset("vaswani")

br = pt.BatchRetrieve.from_dataset("trec-deep-learning-passages", "terrier-stemmed-text")

```

**Comment by cmacdonald** [comment]
Or 
```python
br = pt.BatchRetrieve.from_dataset("trec-deep-learning-passages", "stemmed-text")
```

because BatchRetrieve knows that it needs an index with variant prefix terrier.

This means we could also have (hypothetically) 
```python
ANCEFactory.from_dataset("trec-deep-learning-passages", "model-variant")
```
which would correspond to:
```python
checkpoint = _
indexloc = pt.get_dataset("trec-deep-learning-passages").get_index("ance-model-variant")
ANCEFactory(checkpoint, indexloc)
```

**Comment by seanmacavaney** [comment]
This seems really handy.

I wonder about other args to `BatchRetrieve` and `AnceFactory`. Would those just come after the dataset/index_name combination as `*args, **kwargs`?

```python
pt.BatchRetrieve.from_dataset("trec-deep-learning-passages", "stemmed-text", wmodel="BM25")
ANCEFactory.from_dataset("trec-deep-learning-passages", "model-variant", checkpoint)
```

I suppose for ANCE, you need to use the same checkpoint that generated the index, so this could be done automatically. But where would this be defined?

Should there be some priority/default for the index_name for each dataset? I guess the default would need to be by dataset-and-prefix. If there's only one with the prefix, it could be inferred. But if more were added over time, this could break existing code unless a default is defined.

**Comment by cmacdonald** [comment]
> Would those just come after the dataset/index_name combination as *args, **kwargs?

Yes, I think so

> I suppose for ANCE, you need to use the same checkpoint that generated the index, so this could be done automatically. But where would this be defined?

I'm guessing each implementor of `from_dataset()` would know how to parse what is returned from `dataset.get_index()`.

So in the case of ANCEFactory, get_index() would return a tuple??

>Should there be some priority/default for the index_name for each dataset? I guess the default would need to be by dataset-and-prefix. If there's only one with the prefix, it could be inferred. But if more were added over time, this could break existing code unless a default is defined.

"trec-deep-learning-passages" -- dataset name, 
"stemmed-text" -- index variant, probably "terrier-stemmed-text"
The name would correspond to the variant kwarg of get_index().

I guess you are asking about if `pt.BatchRetrieve.from_dataset("trec-deep-learning-passages")` is a valid option. I am currently thinking no, so that users are forced to be aware of their exact experimental setup?

**Comment by seanmacavaney** [comment]
> I am currently thinking no, so that users are forced to be aware of their exact experimental setup?

Sounds fair, but potentially a tad inconvenient. (You'd need to know both the dataset ID and the index variant string. A standard naming convention for the variants across datasets would help with this though.)

Should the case without variant not be permitted then? Vaswani could have a non-stemmed index as well, for instance.

```python
br = pt.BatchRetrieve.from_dataset("vaswani")
```

I don't think I'm actually in favor of this, but maybe the variant name could be built from arguments? Like so:

```python
pt.BatchRetrieve.from_dataset("trec-deep-learning-passages", stemmer='porter', stops='en')
```

Maybe this could either (1) download if available, or (2) build one based on those specifications if not available.

**Comment by cmacdonald** [comment]
OK, lots for me to mull over here.

**Comment by cmacdonald** [comment]
```python
pt.BatchRetrieve.from_dataset("trec-deep-learning-passages", stemmer='porter', stops='en')
```
This is tricky, as there are a multitude of possible options. What about when there is a deepct or doc2query index? And where should that come in the naming convention?

**Comment by cmacdonald** [comment]
Assuming that we don't need to backup the indices, I have identified a hosting area.
