### ISSUE TITLE
`num_results` for `BatchRetrieve` not working

### ISSUE THREAD

**Issue by DayalStrub** [terrier-org/pyterrier#140]
Currently (if pip installing pyTerrier from github), `num_results` for `BatchRetrieve` is not actually affecting the number of results returned.

Having had a look with a friend, I think it's because `retrieved_set_size` is not set and [this line](https://github.com/terrier-org/pyterrier/blob/43991d6e5acbbc0ef96d48055b38cb013fb379e4/pyterrier/batchretrieve.py#L114) should be un-commented.

I'm happy to open a PR, but unsure whether I'm missing some underlying (Terrier) reason for that line being commented out.

**Comment by cmacdonald** [comment]
Thanks for the report. The problem is `matching.retrieved_set_size` is a global property in Terrier, and changing can impact all BatchRetrieve instances. I think best way is to fix this upstream in Terrier.

In the meantime, something like `pt.ApplicationSetup.setProperty("matching.retrieved_set_size", "2000")` (not the string form of 2000) should have the desired effect, possibly with num_results.  I'll open a Terrier issue, and update here its resolved upstream.

**Comment by DayalStrub** [comment]
Thanks for the explanation. I had gotten it to work by just copying the line in the source code, but had then only checked that I could lower the number of results returned, which worked, and therefore didn't spot that it was global.

**Comment by cmacdonald** [comment]
To *reduce* the number of results retrieved, you can apply the `%` rank cutoff operator.

**Comment by cmacdonald** [comment]
Addressed for v0.6. Thanks!

**Comment by hadifar** [comment]
Using `pyterrier 0.8.0` and still cannot retrieve all documents. 

```
bm25 = pt.BatchRetrieve(index, wmodel='bm25',num_results=400)
output = bm25.transform(queries[:10])

```

I'm expecting the output length be `400*10` but it is less than that. Any fix for this? I follow your recommendation `pt.ApplicationSetup.setProperty("matching.retrieved_set_size", "400")` but it didn't work.

Thanks

**Comment by seanmacavaney** [comment]
Hi @hadifar,

`num_results` is an upper bound for the number of results returned per query. If a query doesn't match that many documents, fewer will be returned. E.g., if the query is "foo", but only 10 documents contain "foo", it will only return 10 results. If the query is "foo bar", but only 50 documents contain either the term "foo" or "bar" (queries are disjunctive by default), it will only return 50 results.

Hope this helps!

**Comment by hadifar** [comment]
Thanks for your reply @seanmacavaney 

Is there any workaround to return all documents?

**Comment by seanmacavaney** [comment]
Hmmm, how would other documents be chosen? Since they all have the same (nil) ranking score, they'd all be tied as equally unrelated to the query. Would you just expect the backfilled results to just be the ones with the lowest docid?

**Comment by hadifar** [comment]
Yes, something like that. Since they all have the same ranking score we can set null for the `rank` and `score` columns.

**Comment by cmacdonald** [comment]
Its possible to get the docnos of document as follows:
`index.getMetaIndex().getItems("docno", [0,1])`

So if this is your desired way to backfill, then it would be easy to write an pt.apply transformer to do so.

No plan to change the current semantics.
