### ISSUE TITLE
PRF snapshot url not found

### ISSUE THREAD

**Issue by Guzpenha** [terrier-org/pyterrier#141]
I am trying to run RM3 and I get the following error:

> urllib.error.HTTPError: HTTP Error 404: Not Found
> [...]
> ValueError: Could not fetch https://repo1.maven.org/maven2/org/terrier/terrier-prf/0.0.1-SNAPSHOT/terrier-prf-0.0.1-SNAPSHOT.jar

When running this line:
`pt.init(boot_packages=["org.terrier:terrier-prf:0.0.1-SNAPSHOT"])`

**Comment by cmacdonald** [comment]
The correct incantation is at:
https://pyterrier.readthedocs.io/en/latest/rewrite.html#rm3

The error message will change in the next release.

Craig
________________________________
From: Gustavo Penha ***@***.***>
Sent: 19 April 2021 12:29
To: terrier-org/pyterrier ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [terrier-org/pyterrier] PRF snapshot url not found (#141)


I am trying to run RM3 and I get the following error:

urllib.error.HTTPError: HTTP Error 404: Not Found
[...]
ValueError: Could not fetch https://repo1.maven.org/maven2/org/terrier/terrier-prf/0.0.1-SNAPSHOT/terrier-prf-0.0.1-SNAPSHOT.jar

When running this line:
pt.init(boot_packages=["org.terrier:terrier-prf:0.0.1-SNAPSHOT"])

**Comment by Guzpenha** [comment]
Thanks Craig !!
