### ISSUE TITLE
AttributeError: module 'pyterrier' has no attribute 'init'

### ISSUE THREAD

**Issue by Tooba-ts1700550** [terrier-org/pyterrier#142]
I am trying to run pyterrier using the documentation:
```
import pyterrier as pt
pt.init()
```

but I get the following error:

`AttributeError: module 'pyterrier' has no attribute 'init'
`
Please help.

**Comment by cmacdonald** [comment]
You have run `pip install pyterrier` not `pip install python-terrier`

**Comment by Tooba-ts1700550** [comment]
Yes, I did that, still same problem

**Comment by cmacdonald** [comment]
You need to pip uninstall pyterrier and then restart your notebook kernel.

**Comment by Tooba-ts1700550** [comment]
yes I already did that, same problem

**Comment by cmacdonald** [comment]
If `pt.http_result` doesnt return an error and `pt.init()` does, then you are still importing the wrong pyterrier (i.e. https://github.com/dfurtado/pyterrier) not this package.

**Comment by Tooba-ts1700550** [comment]
pt.http_result doesnt return an error and pt.init() does.
I tried uninstalling python-terrier, and pyterrier, reinstalled pyterrier, restarted the kernel, restarted the computer even, but still the same error!
What should I do?

**Comment by cmacdonald** [comment]
>reinstalled pyterrier

To be clear, you must run run `pip install python-terrier`

If you still have issues, if you are using Anaconda Python, make a new conda env and  run `pip install python-terrier` *in that environment*. For other Python distributions, you can try virtualenv (which I have no experience of).

**Comment by Tooba-ts1700550** [comment]
Thank you, it works fine now.

**Comment by cmacdonald** [comment]
We're looking at a warning for new users: https://github.com/dfurtado/pyterrier/issues/19

**Comment by cmacdonald** [comment]
Thanks to the kind maintainer of the other package, there is now a warning, and a link to a wiki page.

![image](https://user-images.githubusercontent.com/620938/116267314-36101280-a774-11eb-8abc-152b40b31216.png)
