### ISSUE TITLE
Error in msmarco passage indexing

### ISSUE THREAD

**Issue by Tooba-ts1700550** [terrier-org/pyterrier#143]
While trying to create index for `trec-deep-learning-passages` , Im getting this error:

```
12:24:19.529 [main] WARN  o.t.s.indexing.LexiconBuilder - No temporary lexicons to merge, skipping
12:24:19.557 [main] ERROR o.t.structures.indexing.Indexer - Index has no terms. Inverted index creation aborted.
```

I am following the example code from the docs:
```
dataset = pt.get_dataset("trec-deep-learning-passages")
indexer = pt.TRECCollectionIndexer("./index")
# this downloads the file msmarco-docs.trec.gz
indexref = indexer.index(dataset.get_corpus())
```

**Comment by cmacdonald** [comment]
HI Tooba,

"trec-deep-learning-passages" is a .tsv file, which TRECCollectionIndexer wont understand.

There is an example in the documentation:

https://pyterrier.readthedocs.io/en/latest/text.html#indexing-and-retrieval-of-text-in-terrier-indices

I dont think there is an example showing using "trec-deep-learning-passages" using  pt.TRECCollectionIndexer

In due course, we're planning to provide more example notebooks and pre-built indices, including for this corpus.

Craig

________________________________
From: Tooba ***@***.***>
Sent: 21 April 2021 10:27
To: terrier-org/pyterrier ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [terrier-org/pyterrier] Error in msmarco passage indexing (#143)


While trying to create index for trec-deep-learning-passages , Im getting this error:

12:24:19.529 [main] WARN  o.t.s.indexing.LexiconBuilder - No temporary lexicons to merge, skipping
12:24:19.557 [main] ERROR o.t.structures.indexing.Indexer - Index has no terms. Inverted index creation aborted.


I am following the example code from the docs:

dataset = pt.get_dataset("trec-deep-learning-passages")
indexer = pt.TRECCollectionIndexer("./index")
# this downloads the file msmarco-docs.trec.gz
indexref = indexer.index(dataset.get_corpus())

**Comment by Tooba-ts1700550** [comment]
Thank you for the link.

I tried it, the following line gives an error

```
with pt.io.autoopen(dataset.get_corpus()[0], 'rt') as corpusfile:
       ^
SyntaxError: invalid syntax
```

**Comment by cmacdonald** [comment]
dataset = pt.get_dataset(("trec-deep-learning-passages")

->

dataset = pt.get_dataset("trec-deep-learning-passages")

I will fix the documentation
________________________________

**Comment by Tooba-ts1700550** [comment]
I get this output:

```
12:56:52.241 [ForkJoinPool-1-worker-3] WARN  o.t.structures.indexing.Indexer - Adding an empty document to the index (500080) - further warnings are suppressed
13:15:07.134 [ForkJoinPool-1-worker-3] WARN  o.t.structures.indexing.Indexer - Indexed 5 empty documents
```
I think still the indexes are empty.

**Comment by cmacdonald** [comment]
Only 5 empty passages? Seems OK to me.

Craig

**Comment by cmacdonald** [comment]
So it works?

**Comment by Tooba-ts1700550** [comment]
Thank you very much, it works now.

**Comment by Tooba-ts1700550** [comment]
I am not sure what happened, but suddenly the passage indexing code gives the following error, it was working fine until 2 hours ago. I'm using the exact same code from the link you shared. Maybe some package version issue?

```
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pyterrier/index.py", line 668, in _write_fifos
    for doc in it:
  File "<ipython-input-2-26afc0e98a1a>", line 8, in msmarco_generate
    with pt.io.autoopen(dataset.get_corpus()[0], 'rt') as corpusfile:
  File "/usr/local/lib/python3.7/dist-packages/pyterrier/datasets.py", line 231, in get_corpus
    return pt.io.find_files(self._get_all_files("corpus", **kwargs))
  File "/usr/local/lib/python3.7/dist-packages/pyterrier/datasets.py", line 211, in _get_all_files
    tarobj.extract(intarfile, path=self.corpus_home)
  File "/usr/lib/python3.7/tarfile.py", line 2033, in extract
    tarinfo = self.getmember(member)
  File "/usr/lib/python3.7/tarfile.py", line 1752, in getmember
    tarinfo = self._getmember(name)
  File "/usr/lib/python3.7/tarfile.py", line 2327, in _getmember
    members = self.getmembers()
  File "/usr/lib/python3.7/tarfile.py", line 1763, in getmembers
    self._load()        # all members, we first have to
  File "/usr/lib/python3.7/tarfile.py", line 2350, in _load
    tarinfo = self.next()
  File "/usr/lib/python3.7/tarfile.py", line 2281, in next
    self.fileobj.seek(self.offset - 1)
  File "/usr/lib/python3.7/gzip.py", line 379, in seek
    return self._buffer.seek(offset, whence)
  File "/usr/lib/python3.7/_compression.py", line 143, in seek
    data = self.read(min(io.DEFAULT_BUFFER_SIZE, offset))
  File "/usr/lib/python3.7/gzip.py", line 493, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

**Comment by cmacdonald** [comment]
Probably the tar file is corrupt in ~/.pyterrrier/corpora
You can remove it and it will download again

**Comment by Tooba-ts1700550** [comment]
Thank you, it works this way!
