### ISSUE TITLE
Difference between pipelines

### ISSUE THREAD

**Issue by Tooba-ts1700550** [terrier-org/pyterrier#150]
I am potentially new to IR and it might be a basic question. I want to understand what is the difference between the following two pipelines:

```
BM25 >> pt.text.get_text(indexref, "text") >> monoT5

BM25 >>  monoT5
```

**Comment by cmacdonald** [comment]
Depends on the definition of BM25 variable. BatchRetrieve can be configured to retrieve document text during retrieval (metadata=["docno", "text"], or you can get it later using get_text().

**Comment by Tooba-ts1700550** [comment]
So if this is how BM25 is defined:
```
BM25 = pt.BatchRetrieve(index, wmodel="BM25")
monoT5 = MonoT5ReRanker()
```
Then, what is the difference between the two commands ?

**Comment by cmacdonald** [comment]
`pt.BatchRetrieve(index, wmodel="BM25")` will not retrieve any text metadata. So you either need to add `metadata=["docno", "text"]`, or you can get it later using get_text(). Please see https://pyterrier.readthedocs.io/en/latest/text.html
