### ISSUE TITLE
requiring explanation in docs

### ISSUE THREAD

**Issue by Tooba-ts1700550** [terrier-org/pyterrier#152]
How to get the number of documents produced by a pipeline result?
For example I want to know what is the count returned by the intersection of BM25 and PL2:
`res_intersection = (BM25_br & PL2_br).transform(topics)
`
referring to docs at [https://pyterrier.readthedocs.io/en/latest/operators.html]

**Comment by cmacdonald** [comment]
res_intersection is a Pandas dataframe - all the normal dataframe operators apply, incl `len()`.

**Comment by Tooba-ts1700550** [comment]
I tried it already, `res_intersection.len()`, it gives the following error:

`AttributeError: 'RankCutoffTransformer' object has no attribute 'len'`

**Comment by cmacdonald** [comment]
Your code doesnt match the datatypes. This works for me:

```python
BM25 = pt.BatchRetrieve(index, wmodel="BM25")
DLM  = pt.BatchRetrieve(index, wmodel="DirichletLM")
res =  (BM25 & DLM).transform(topics)
len(res)
```

Furthermore, as noted in #153, you cannot apply a rank cutoff to the output of an set operator. It is a set - there are no ranks.

**Comment by Tooba-ts1700550** [comment]
Thank you!
