### ISSUE TITLE
Error with intersection operator

### ISSUE THREAD

**Issue by Tooba-ts1700550** [terrier-org/pyterrier#153]
I am trying to experiment with intersection and union operators:
```

BM25 = pt.BatchRetrieve(index, wmodel="BM25")
DLM  = pt.BatchRetrieve(index, wmodel="DirichletLM")

BM25_i_DLM = (BM25|DLM).transform(dataset.get_topics("test-2020")) %1000

exp = pt.Experiment(
  [BM25_i_DLM],
  dataset.get_topics("test-2020"),
  dataset.get_qrels("test-2020"),
  names=["BM25_i_DLM"],
  eval_metrics=["map", "recip_rank", "P.10", "ndcg_cut.10"]
)
```

This gives the following error:
`AssertionError: require rank to be present in the result set`

**Comment by cmacdonald** [comment]
What were you expecting to happen?

This doesnt really make sense:
` (BM25|DLM).transform(dataset.get_topics("test-2020")) %1000`

`(BM25|DLM)` is a transformer
` (BM25|DLM).transform(dataset.get_topics("test-2020"))` is a resultset (Pandas dataframe)

its then being coerced back to a transformer source, and applying a rank cutoff.

However, as clearly documented in the operator documentation (see https://pyterrier.readthedocs.io/en/latest/operators.html#set-intersection-and-intersection), there are no ranks or scores returned by an intersection or union, so you cannot apply a rank cutoff operator.

I must please ask you to read the relevant documentation before posting.

**Comment by Tooba-ts1700550** [comment]
I was expecting to get only top 1000 intersected documents.
