### ISSUE TITLE
Indexing of UTF8 text (Bengali) yields empty documents.

### ISSUE THREAD

**Issue by soldni** [terrier-org/pyterrier#158]
**Describe the bug**
I am trying to index Bengali text from Wikipedia using PyTerrier. My workflow performs tokenization using SpaCy prior to ingesting documents, and I've set `termpipelines` to  `""` and `tokenisation` to `UTFTokeniser` as recommended in the documentation. However, when I try to index the data, Terrier reports that empty documents have been received. I've verified that the same configuration works when English documents are used, so I am not sure what is going on. 

**To Reproduce**
Minimal Colab notebook to reproduce the issue [is available here.](https://colab.research.google.com/drive/1w-Jbpo8u98-pM0d3Lottu4r4fw5jy675#scrollTo=P0ArHA--aCqJ) Run all cells, see output of last cells for error message. 

**Expected behavior**
I would expect documents to be properly indexed. 

**Documentation and Issues**
 - [x] I have checked the [PyTerrier documentation](https://pyterrier.readthedocs.io/en/latest/) for relevant content
 - [x] I have checked for previous relevant [PyTerrier issues](https://github.com/terrier-org/pyterrier/issues)

**Screenshots**
N/A

**Additional context**
N/A

**Comment by cmacdonald** [comment]
Thanks for the concrete minimal example @soldni, we'll look into this for you.

**Comment by cmacdonald** [comment]
`indexer.setProperty("tokenisation", "UTFTokeniser")`
should be
`indexer.setProperty("tokeniser", "UTFTokeniser")`

After I made the change, indexing and retrieval worked as expected.

![image](https://user-images.githubusercontent.com/620938/118008316-d9e8e900-b344-11eb-9d35-30e3227ab8d8.png)

Let me know if you find some documentation that has the wrong property specified.

**Comment by soldni** [comment]
Ah! Great catch, @cmacdonald! Documentation is correct, but maybe slightly prone to errors. On [this page](https://pyterrier.readthedocs.io/en/latest/terrier-indexing.html#indexing-configuration), it says:

> - *tokenisation*: Similarly, tokenisation is controlled by the “*tokeniser*” property. [EnglishTokeniser](http://terrier.org/docs/current/javadoc/org/terrier/indexing/tokenisation/EnglishTokeniser.html) is the default tokeniser. Other tokenisers are listed in [org.terrier.indexing.tokenisation](http://terrier.org/docs/current/javadoc/org/terrier/indexing/tokenisation/package-summary.html) package. For instance, use *indexer.setProperty(“tokeniser”, “UTFTokeniser”)* when indexing non-English text.

I must have read it quickly and assumed that `tokenisation`, not `tokeniser` was the key. 

I'll close the issue.

**Comment by cmacdonald** [comment]
Thanks, I will review that bullet of the documentation. I think the opening rubric could indeed be tokeniser. Longer term tokeniser choice should be an index constructor option.
