### ISSUE TITLE
`blocks=True` throws a `java.lang.ClassNotFoundException`

### ISSUE THREAD

**Issue by villatoroe** [terrier-org/pyterrier#161]
When trying to use the "record the positions" feature during the index construction, i.e., `blocks=True` but I'm getting some strange warning

This is how I setup the pipeline, nothing strange: 

`iter_indexer = pt.IterDictIndexer(ami_index, blocks=True) `  
`index_ref = iter_indexer.index(ami_corpus_generate(files), fields=('text',), meta=['docno','lineNum','channel','text'])`

Notice the ` blocks=True` in the constructor. 
The generated output looks normal, something like this is generated when getting the statistics of the index: 

`Number of documents: 134671`
`Number of terms: 7662`
`Number of postings: 363503`
`Number of fields: 1`
`Number of tokens: 418262`
`Field names: [text]`
`Positions:   true`

However, I got some strange exception from Java (when debugging is on) which appears as follows: 

`java.lang.ClassNotFoundException: org.terrier.terms.Positions`
	`at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)`
	`at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)`
	`at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)`
	`at java.base/java.lang.Class.forName0(Native Method)`
	`at java.base/java.lang.Class.forName(Class.java:398)`
	`at org.terrier.utility.ApplicationSetup.getClass(ApplicationSetup.java:416)`
	`at org.terrier.structures.indexing.Indexer.load_pipeline(Indexer.java:314)`
	`at org.terrier.structures.indexing.Indexer.init(Indexer.java:193)`
	`at org.terrier.structures.indexing.classical.BlockIndexer.<init>(BlockIndexer.java:293)`
	`at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)`
	`at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)`
	`at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)`
	`at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)`
	`at org.terrier.python.ParallelIndexer$1.apply(ParallelIndexer.java:58)`
	`at org.terrier.python.ParallelIndexer$1.apply(ParallelIndexer.java:52)`
	`at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)`
	`at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)`
	`at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)`
	`at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)`
	`at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)`
	`at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)`
	`at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)`
	`at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)`
	`at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)`

`12:38:45.894 [ForkJoinPool-11-worker-3] WARN  o.t.structures.indexing.Indexer - Adding an empty document to the index (EN2001a) - further warnings are suppressed`

	`at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)`
	`at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)`
	`at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)`
	`at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)`
	`at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:558)`
	`at org.terrier.python.ParallelIndexer$3.call(ParallelIndexer.java:132)`
	`at org.terrier.python.ParallelIndexer$3.call(ParallelIndexer.java:129)`
	`at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)`
	`at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)`
	`at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)`
	`at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)`
	`at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)`
	`at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)`

I'm not sure why this exception is thrown and if it means that positions are not being recorded. 
Best,

**Comment by cmacdonald** [comment]
can you check if you did any setProperty("termpipelines", ...) anywhere else in your code? (even if you later deleted it). 

I'm struggling to see where this came from. Terrier Properties are global, so there is a chance that an earlier attempt could be copied over.

Give a look at the output of
```python
pt.ApplicationSetup.getProperties().toString()
```
?

**Comment by cmacdonald** [comment]
Properties are a big set of global configuration used by Terrier. We are _trying_ to make it such that people in PyTerrier don't need to know about them. Its also an aspiration to remove them entirely from Terrier (an aspiration that has existed for at least 15 years). 

As you have `termpipelines=Stopwords,PorterStemmer`, I guess you must have restarted your notebook. Does indexing now work?

**Comment by villatoroe** [comment]
Hi, 
Thanks for the clarification. 
The indexing works, even when the exception was being thrown, or at least that seems to be the case. However,  I did manage to test if the positions info was saved or not.

**Comment by cmacdonald** [comment]
`Positions: true` is indicative of positions being saved.

Also executing a query using phrases will throw an error if positions are not present:

```python
br = pt.BatchRetrieve(index)
br.search(' "chemical reactions" ')
```

Closing as not-a-bug
