### ISSUE TITLE
How to create index with DataFrame 

### ISSUE THREAD

**Issue by deepkshikha** [terrier-org/pyterrier#162]
I Have done the following Query DataFrame (pdf)

                query  qid
0       refrigerators    0
1               mulch    1
2   bathroom vanities    2
3        ceiling fans    3
4             plywood    4
..                ...  ...
95       patio chairs   95
96          wallpaper   96
97       screen doors   97
98        deck boards   98
99    upright freezer   99

And document dataframe as (QueryDF)
p_product_catalog_search  docno 

Created indexref as below 
indexref = pd_indexer.index(pdf["p_product_catalog_search"],pdf["docno"])

then next step

index = pt.IndexFactory.of("./pd_index2/data.properties")
tf_idf = pt.BatchRetrieve(index, wmodel="TF_IDF")
bm25 = pt.BatchRetrieve(index, wmodel="BM25")
pl2 = pt.BatchRetrieve(index, wmodel="PL2")

When trying last stage with query 
pt.Experiment([tf_idf, bm25, pl2],  queryPDF, pdf,eval_metrics=["map"])

It gave an error

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-154-2bd5afc0768f> in <module>
----> 1 pt.Experiment([tf_idf, bm25, pl2],  queryPDF, pdf,eval_metrics=["map"])

/opt/conda/lib/python3.7/site-packages/pyterrier/pipelines.py in Experiment(retr_systems, topics, qrels, eval_metrics, names, perquery, dataframe, baseline, correction, correction_alpha, highlight, round)
    147             names.append(str(system))
    148 
--> 149     qrels_dict = Utils.convert_qrels_to_dict(qrels)
    150     all_qids = topics["qid"].values
    151 

/opt/conda/lib/python3.7/site-packages/pyterrier/utils.py in convert_qrels_to_dict(df)
    218         run_dict_pytrec_eval = defaultdict(dict)
    219         for row in df.itertuples():
--> 220             run_dict_pytrec_eval[row.qid][row.docno] = int(row.label)
    221         return(run_dict_pytrec_eval)
    222 

AttributeError: 'Pandas' object has no attribute 'label'

Please suggest where I am doing wrong

**Comment by cmacdonald** [comment]
hi @deepkshikha 

I think you need to have clearly separated in your mind three different things:
 (a) the documents (e.g. columns "docno" and "text")
 (b) the queries (e.g. columns "qid" and "query),  and
 (c) the qrels or labels (columns "qid", "docno" and "label").

At present, I think you are mixing at least two of these concepts.

**Comment by deepkshikha** [comment]
Thanks, The document is little confusing. 

Here in Terrier etrival what would go for topic and qrels for custom data. Column  name or the data frame column value

pt.Experiment([tf_idf, bm25, pl2], topic, qrels, eval_metrics=["map"])

**Comment by cmacdonald** [comment]
You need to form a _test collection_ - queries with known relevant documents, i.e. a ground truth.  See chapter 8 in https://ciir.cs.umass.edu/downloads/SEIRiP.pdf

If you don't have such a ground truth, pt.Expeirment() cannot be used.
