### ISSUE TITLE
5.5 jar not found

### ISSUE THREAD

**Issue by Guzpenha** [terrier-org/pyterrier#166]
**Describe the bug**
pt.init() tries to fetch 5.5 jar and it does not find it.

**To Reproduce**
if not pt.started():
  pt.init()

**Expected behavior**
ValueError: Could not fetch https://repo1.maven.org/maven2/org/terrier/terrier-assemblies/5.5/terrier-assemblies-5.5-jar-with-dependencies.jar

**Documentation and Issues**
 - [x] I have checked the [PyTerrier documentation](https://pyterrier.readthedocs.io/en/latest/) for relevant content
 - [x] I have checked for previous relevant [PyTerrier issues](https://github.com/terrier-org/pyterrier/issues)

**Comment by seanmacavaney** [comment]
Thanks for posting! We're waiting for terrier 5.5 to appear on maven.

The strange thing is that that [maven metadata file](https://repo1.maven.org/maven2/org/terrier/terrier-assemblies/maven-metadata.xml) doesn't match what's actually available.

```xml
<metadata>
  <groupId>org.terrier</groupId>
  <artifactId>terrier-assemblies</artifactId>
  <versioning>
    <latest>5.5</latest>
...
```

**Comment by seanmacavaney** [comment]
A workaround in the meantime is to specify the previous terrier version on init:

```python
pt.init(version=5.4)
```

**Comment by cmacdonald** [comment]
Or `pt.init(version='snapshot')`

It seems that MavenCentral had sync problems yesterday - I have asked them to investigate: 

https://issues.sonatype.org/browse/MVNCENTRAL-6739

**Comment by Guzpenha** [comment]
Thanks, I am using `pt.init(version='snapshot')` for now !

**Comment by Guzpenha** [comment]
It seems to be working now https://repo1.maven.org/maven2/org/terrier/terrier-assemblies/5.5/ :) !

**Comment by cmacdonald** [comment]
For me, the jar file is shown in the listing, but fetching https://repo1.maven.org/maven2/org/terrier/terrier-assemblies/5.5/terrier-assemblies-5.5-jar-with-dependencies.jar still fails.

**Comment by Guzpenha** [comment]
Oh true, I was still using snapshot `Downloading terrier-assemblies 5.x-SNAPSHOT`

**Comment by cmacdonald** [comment]
Now resolved by Sonatype folks :-)

**Comment by cmacdonald** [comment]
Thank for the fast report @Guzpenha
