### ISSUE TITLE
Boolean retrieval

### ISSUE THREAD

**Issue by Fatima-Haouari** [terrier-org/pyterrier#167]
Hi,
We are planning to use PyTerrier as a tool to teach an information retrieval course. In addition to indexing, retrieval and evaluation we are interested to know if boolean retrieval is supported. Kindly advise.

**Comment by cmacdonald** [comment]
Hi Fatima,

Thanks for your interest. The BatchRetrieve class supports both of Terrier's query languages, which are discussed here:

https://github.com/terrier-org/terrier-core/blob/5.x/doc/querylanguage.md

Viz teaching - You may also want to peruse the part 1 and part 2 notebooks from our ECIR2021 tutorial, which bear some resemblance to the Notebooks we use with our own undergraduate classes.

https://github.com/terrier-org/ecir2021tutorial

Any more questions, let us know.

Craig

**Comment by Fatima-Haouari** [comment]
Great! I appreciate your quick response. 
The ECIR tutorial notebooks are really useful. Thanks for your efforts.

**Comment by Fatima-Haouari** [comment]
Hi again,
Just to make sure I am doing it correctly.  I am trying to use the batchRetrieve for boolean retrieval using the user query language you shared above.
I used ECIR notebook1 to index the 3 documents as an example and used the below queries.

![image](https://user-images.githubusercontent.com/71061623/119240997-3a093780-bb5c-11eb-9557-f1a8371890d2.png)

Could please advise why for query2 which is supposed to get only the documents having both "document" AND "another" it is funtioning as an OR operation instead. The same for query1 which excluded documents containing "first" but did not function as an AND operation for the other terms although the + sign was added.

Is there any configuration I should do? by looking at the BatchRetrieve class code the "terrierql": "on" is on by default.

**Comment by cmacdonald** [comment]
My earlier reply was sent very rapidly.  Please check carefully the aforementioned querylanguage.md, as the Terrier QL contains no mention of AND. It does have positive requirement which can be expressed using the + operator.

Something approximating AND fa be achieved using the matchop query language, using the #band operator. If you really need this I can provide an example.

**Comment by Fatima-Haouari** [comment]
Thanks. It would be great if you can provide an example of using the #band operator.

**Comment by cmacdonald** [comment]
```python
br = pt.BatchRetrieve(pt.get_dataset("vaswani").get_index(), wmodel="CoordinateMatch")
br.search("#band(chemical reactions)")
```

Hope this helps.

**Comment by Fatima-Haouari** [comment]
Great. Thanks.
