### ISSUE TITLE
Loading my own saved index

### ISSUE THREAD

**Issue by Fatima-Haouari** [terrier-org/pyterrier#168]
Hi,

I am using Pyterrier for indexing and retrieval, it is working perfectly from me. However when I exported my index and tried to load it again I am getting an exception. Please advise regarding the below.

![image](https://user-images.githubusercontent.com/71061623/119459252-2faa9180-bd46-11eb-8912-24507bd3e08a.png)

I tried also using the BatchRetrieve by sending the data.properties file and I am getting the same exception.

![image](https://user-images.githubusercontent.com/71061623/119459567-7c8e6800-bd46-11eb-9e44-b1780cfe604e.png)

**Comment by cmacdonald** [comment]
Try `pt.BatchRetrieve("./evetarIndex/data.properties", wmodel="BM25")`

**Comment by cmacdonald** [comment]
or the full path.

**Comment by Fatima-Haouari** [comment]
Thanks for your quick response. Unfortunately I already tried your mentioned solutions but still not working.

**Comment by Fatima-Haouari** [comment]
Solved the issue. Thanks a lot.
