### ISSUE TITLE
module 'pyterrier' has no attribute 'GridSearch'

### ISSUE THREAD

**Issue by jflucph** [terrier-org/pyterrier#170]
I am trying to run your example from Tuning Transformer Pipelines in the documentation, but I get an attribute error: module 'pyterrier' has no attribute 'GridSearch'

Any suggestions? 

Initializing PyTerrier: "PyTerrier 0.5.0 has loaded Terrier 5.5 (built by craigmacdonald on 2021-05-20 13:12)"

code: 
```
BM25 = pt.BatchRetrieve(index, wmodel="BM25", controls={"c" : 0.75})
pt.GridSearch(
    BM25,
    {BM25 : {"c" : [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1 ]}},
    train_topics,
    train_qrels,
    "map")
```

**Comment by cmacdonald** [comment]
You need PyTerrier 0.6 - can you upgrade?

**Comment by cmacdonald** [comment]
Command would be `pip install -U python-terrier`

**Comment by cmacdonald** [comment]
Fixed?

**Comment by jflucph** [comment]
Yes, upgrading did it! Thank you for your fast reply!!
