### ISSUE TITLE
How to retrieve Expanded query with pyTerrier?

### ISSUE THREAD

**Issue by deepkshikha** [terrier-org/pyterrier#171]
Created pipeline and used validation data as below

bm25 = pt.BatchRetrieve(index, wmodel="BM25")
rm3_pipe = bm25 >> pt.rewrite.RM3(index) >> bm25
pt.Experiment([bm25, rm3_pipe],
            ptopic_taildf,qrel_taildf,
            ["map","recall"]
            )
which is giving score metrics as below
<img width="1139" alt="Screenshot 2021-05-27 at 7 30 20 PM" src="https://user-images.githubusercontent.com/13184577/119839771-0ba3a780-bf22-11eb-98cf-71f933abc1f3.png">

How could we extract or find what is the expanded query for the given query?

**Comment by cmacdonald** [comment]
The expanded query should be in any results dataframes returned by rm3_pipe:
```python
rm3_pipe.search("my query")
rm3_pipe.transform(ptopic_taildf)
```
If you look at the query column it shows the expanded query. query_0 shows the original query.

If you want ONLY the query, you can do that by inspecting the output of only the first 2 stages, i.e. 
```python
#assuming that
rm3_12 = bm25 >> pt.rewrite.RM3(index)
rm3_12.search("my query")
#OR
rm3_12.transform(ptopic_taildf)
```

rm3_12 can also be obtained by slicing the `>>`:
```python
rm3_12 = rm3_pipe[0]
````

HTH

**Comment by deepkshikha** [comment]
Thanks for the quick response!, Appreciated it.  But not sure why the result is looking odd.
<img width="1139" alt="Screenshot 2021-05-27 at 8 27 16 PM" src="https://user-images.githubusercontent.com/13184577/119849101-f6cb1200-bf29-11eb-80b1-111690aa8f33.png">

**Comment by cmacdonald** [comment]
Query terms are weighted - this is normal PRF. Terms returned by PRF are also stemmed.
Applypipeline ensures that terms are not stemmed twice by Terrier.

**Comment by deepkshikha** [comment]
So this is an expanded query itself with a weight attached to terms??? Also, I can't find a column query_0

**Comment by cmacdonald** [comment]
> So this is an expanded query itself with a weight attached to terms

Yes

Here is an example with PyTerrier 0.6.0. You can upgrade to get the query_0 column.

```
>>> pt.init()
PyTerrier 0.6.0 has loaded Terrier 5.5 (built by craigmacdonald on 2021-05-20 13:12)
No etc/terrier.properties, using terrier.default.properties for bootstrap configuration.
>>> index = pt.get_dataset("vaswani").get_index()
>>> bm25 = pt.BatchRetrieve(index, wmodel='BM25')
>>> qe = pt.rewrite.Bo1QueryExpansion(index)
>>> qe_pipe = bm25 >> qe >> bm25
>>> qe_pipe.search("chemical reactions")
    qid  docid  docno  rank      score             query_0                                              query
0     1   9373   9374     0  22.810692  chemical reactions  applypipeline:off chemic^1.417187407 reaction^...
1     1   8765   8766     1  22.035518  chemical reactions  applypipeline:off chemic^1.417187407 reaction^...
2     1   7048   7049     2  20.183302  chemical reactions  applypipeline:off chemic^1.417187407 reaction^...
3     1   4686   4687     3  17.845710  chemical reactions  applypipeline:off chemic^1.417187407 reaction^...

>>> qe_pipe.search("chemical reactions").iloc[0].query
'applypipeline:off chemic^1.417187407 reaction^1.730852372 ion^0.221591006 balanc^0.211494722 coeffici^0.151187967 ionospher^0.148161192 mai^0.135763969 discuss^0.096222873 photo^0.000000000 investig^0.000000000'
```

**Comment by deepkshikha** [comment]
Thanks a lot were helpful.
