### ISSUE TITLE
alternative caching proposal

### ISSUE THREAD

**Issue by seanmacavaney** [terrier-org/pyterrier#173]
**Is your feature request related to a problem? Please describe.**

When building complex pipelines, it can be beneficial to cache intermediate results. The current `~` caching operator (and [proposed changes](#165)) accomplish this by wrapping a transformer and performing on-disk lookups for each dataframe record. Though there are clear advantages to this approach, there are also several downsides:

 - The entire pipeline needs to be traversed. This can be problematic in cases where there are dependency incompatibilities between libraries, e.g., `pyterrier_t5` and `pyterrier_colbert` require different versions of hgf. Or when experiments are conducted on machines with different hardware configurations advantageous for different steps (e.g., performing retrieval on a machine that has an index on SSD and re-ranking on a machine that has beefy GPUs).
 - Since the lookups are performed by record, they hit the disk multiple times in a potentially random order. For large dataframes, this could get particularly expensive.
 - The cached items are not compressed. Given that some values (e.g., queries) often appear on many rows, this can lead to wasted storage. Adding compression to the current scheme would not be very beneficial because the records are cached individually, so cross-record redundancy cannot be avoided.
 - Transformers need to opt-in to be cached. Caching is done based on the `__repr__`, which may potentially contain some information that doesn't affect results (e.g., `verbose=True`) unless the `__repr__` is constructed such that it only contains things that would affect the cache.

**Describe the solution you'd like**

Have an alternative approach for caching that acts as a pipeline component. The user specifies the file cache path, which stores an entire dataframe (compressed). For instance, it could look like:

```python
pipeline = dph >> FileCache('my_exp/dph') >> \
           monoT5 % 100 >> FileCache('my_exp/dph/monot5.100') >> \
           colbert >> FileCache('my_exp/dph/monot5.100/colbert')
```

Also, introduce a new `short_circuits` transformer method that tells pipelines that everything preceding it can be skipped. This would be `False` by default for all transformers (i.e., should execute), but `True` for `FileCache` when the cache file exists. The `ComposedPipeline.transform` can be updated as follows:

```python
    def transform(self, topics):
        start_idx = 0
        for i, m in enumerate(self.models[::-1]):
            if m.short_circuits():
                start_idx = len(self.models) - i - 1 # start at the short circuiting transformer
                break
        for m in self.models[start_idx:]:
            topics = m.transform(topics)
        return topics
```

This approach has some benefits:
 - The cached results (e.g., in `my_exp/`) can be `rsync`'d across machines without conflicts. This means that experiments can be easily scaled across machines without shared storage, which can be advantageous when machines have different resources or when a bunch of ablations need to be done.
 - Loading from a cache is about as fast as it can get and storage size is managed with file compression.
 - Results from any transformer can be cached, not just those that opt in.

There are several downsides, though, which are things that the current solution does well:
 - It's up to the user to make sure that they contain relevant information to avoid collisions based on cached component's settings. As a simple example, a pipeline where cache files exist *will return the same thing, regardless of what's passed in as topics*. This clearly could lead to some confusion and problems.
 - There can be redundancy across cached files. Consider the case where I try the above pipeline with both DPH and BM25. The monoT5 and colbert work will be re-done for any query-document pairs that are common across the datasets.

**Describe alternatives you've considered**

I considered the current caching operator.

**Additional context**

I successfully used this technique for some recent experiments. I also used a pipeline builder utility for composing pipelines that are cached at each stage and a lazy-initialized transformer component, but I omitted it from this proposal to keep it straightforward.

**Comment by cmacdonald** [comment]
Thanks. Lots of good thought here.  Some initial questions, if I may.

>Since the lookups are performed by record

Not sure what "by record" corresponds to. What is being cached on I think needs to be customisable. In #165, I called this the "cache key" - eg. cache on qid alone, or on qid and query, or on qid, docno, etc. Caching on qid certainly permits compression.

Does `t.short_circuits()` affect any other operators? 

I will probably have more questions.

**Comment by seanmacavaney** [comment]
> by record ... compression

Right, I was thinking mostly about re-rankers there. A first-stage DPH could cache on `qid` (mapping to many records), but a re-ranking monoT5 would need to cache on `(qid,docno)` (mapping to a single record) because otherwise, you could get back records from other first-stage retrievers. Unless I'm missing something...

> Does `t.short_circuits()` affect any other operators

I added this to `ComposedPipeline`:

```python
    def short_circuits(self):
        return any(m.short_circuits() for m in self.models[::-1])
```

which could potentially also generalise to `NAryTransformerBase`? I'd need to think about these cases in more detail.

Returning `False` from `short_circuits` should always be safe though. The worst case is you do work that's just clobbered by `FileCache` later in the pipeline. It's just an optimization. (On that note, maybe should this be done by `.compile()` instead?)

**Comment by seanmacavaney** [comment]
This issue relates to #163 as well

**Comment by albertoueda** [comment]
I would like to add three minor considerations related to this matter (I do not think they deserve a new issue), with regards to the [documentation](https://pyterrier.readthedocs.io/en/latest/operators.html):

1. > In this example, _firstpass_ is cached when it is used in the Experiment evaluation, as well as when it is used in the reranker. 

It's not clear if the second '\~' for _firstpass_ is mandatory or optional to use the cached version. The following sentence may add some confusion because it may look like both the '~'s (_~firstpass_ and _~reranker_) are necessary to cache the experiment outcome.

2. > We also cache the outcome of the Experiment, so that another evaluation will be faster.

Suggestion: "We also cache the outcome of the Experiment (_**~reranker**_), so that (...)"

3. > By default, Pyterrier caches results to ~/.pyterrier/transformer_cache/.

Could it also be configurable to the `PYTERRIER_HOME` ? From the code, I found `HOME_DIR` references only.
