### ISSUE TITLE
QueryParserExeption with complex strings

### ISSUE THREAD

**Issue by wpertsch** [terrier-org/pyterrier#174]
**BatchRetrieval does not work with certain strings**
Strings with certain characters like "/" or "{"

**To Reproduce**
1. **Index:** TFIDF index (chars like "/" and "{" where indexed)
2. **Retrieval:** Batchretrieval with model wmodel="TF_IDF" 
3. **Error:** Traceback (most recent call last):
  File "pyterrier/main.py", line 82, in <module>
    BatchRetriever("{")
  File "pyterrier/main.py", line 76, in BatchRetriever
    res = tf_idf.transform(dataframe)
  File "pyterrier/batchretrieve.py", line 178, in search
    rtr = self.transform(queryDf)
  File "pyterrier/batchretrieve.py", line 205, in transform
    self.manager.runSearchRequest(srq)
  File "jnius/jnius_export_class.pxi", line 857, in jnius.JavaMethod._ _ call _ _
  File "jnius/jnius_export_class.pxi", line 954, in jnius.JavaMethod.call_method
  File "jnius/jnius_jvm_dlopen.pxi", line 91, in jnius.create_jnienv
jnius.JavaException: JVM exception occurred: Failed to process qid 1 '{' org.terrier.querying.parser.QueryParserException

**Expected behavior**
Normal search or transformation was working fine, i was trying to retrieve Text with a bit of Latex-Code and get close to the same results

**Screenshots**
![image](https://user-images.githubusercontent.com/33632714/120189191-515cba80-c217-11eb-8aec-26985017eb2a.png)

**Comment by cmacdonald** [comment]
Hi William

Thanks for your report. My default, Terrier's normal query language assumes queries are well formatted in something approximating a query in a Google-like syntax. 

string.use_utf is VERY old, and shouldnt be used anymore - it has no impact anywhere in Terrier.

I think if your indexed tokens include special characters, you should use the lower-level matchop query language. In that, you can encode tokens using `#base64` operators. See also https://github.com/terrier-org/terrier-core/blob/5.x/doc/querylanguage.md

BatchRetrieve detects queries in the matchop format automatically - see https://github.com/terrier-org/pyterrier/blob/master/pyterrier/batchretrieve.py#L22

**Comment by wpertsch** [comment]
Hello Craig,

Thank you for your fast response and thank you for the comment about string.use_utf. I am quite new to Terrier (especially Pyterrier) and i don't have any idea how to switch the query language in PyTerrier.
I can't finde anything about it in the PyTerrier docs. I tried encoding my dataframe to base24 but this leads to an empty result.
How can i switch to matchop?

**Comment by cmacdonald** [comment]
The query language switch is transparent in PyTerrier - all matchop operators are prefixed with `#`. Let me give an example. 

Let 
```python
br = pt.BatchRetrieve()
query = ["chemical", "reactions"]
```
Then these two search invocations are equivalent:

1.
```python
br.search(' '.join(query))
```

and

2.
```python
def encode(qterms):
  return ' '.join(map(lambda term : "#base64("+ base64.urlsafe_b64encode(bytes(term, "UTF-8")).decode('utf-8') + ")", qterms))
br.search(encode(query))
```

In the latter case, the query is encoded as `#base64(Y2hlbWljYWw=) #base64(cmVhY3Rpb25z)`.



NB: In the process of developing this, I identified a bug in Terrier's parsing of #base64 - see https://github.com/terrier-org/terrier-core/issues/169. This SHOULD work if you use `pt.init(version='snaphot')`.

**Comment by cmacdonald** [comment]
@wpertsch did you get this working?

**Comment by wpertsch** [comment]
hey @cmacdonald,
The snapshot works fine and was eliminating errors. If I try the query you described, searching for a list of tokens, the results are as expected and everything works fine. Searching for longer strings gives back empty results.
What i Am trying to do, is rebuilding a (Java-)Terrier baseline in Python so i know what kind of results i would like to get.
When forming/tokenizing a longer query by hand i don't get the expected results. I know this i probably because the normal tokeniser is doing things different than just cutting on spaces in the given strings.
How can i submit string-querys or is there a way of tokenizing strings before querying?

**Comment by cmacdonald** [comment]
I'm not clear if your problem is indexing side or querying side? You can inspect indexed tokens, e.g. by looking inside the lexicon. 

>When forming/tokenizing a longer query by hand i don't get the expected results.

Which query language?

**Comment by wpertsch** [comment]
Sorry for describing my problem so vaguely.
As I mentioned before, I already have retrieval results which I am trying to reproduce. Before I tried to search for special characters, the results were also flawless. I think I used the "User Query Language" by default.

I think my current problems are on the querying side, because I switched to the "Matching Op Query Language" and now querying with special characters works, but I can't convert longer sentences correctly into the form you described (query = ["chemical", "reactions"]).

For example: how do i query for this:
<TOP>
      <TITLE>Finding value of &lt;span class=&quot;math-container&quot; id=&quot;q_1&quot;&gt;$c$&lt;/span&gt; such that the range of the rational function &lt;span class=&quot;math-container&quot; id=&quot;q_2&quot;&gt;$f(x) = \frac{x^2 + x + c}{x^2 + 2x + c}$&lt;/span&gt; does not contain &lt;span class=&quot;math-container&quot; id=&quot;q_3&quot;&gt;$[-1, -\frac{1}{3}]$&lt;/span&gt;</TITLE>
   </TOP>

**Comment by wpertsch** [comment]
@cmacdonald do you have any idea how I can approach this problem?

**Comment by cmacdonald** [comment]
I'm thinking you need to remove the tags - e.g. https://beautiful-soup-4.readthedocs.io/en/latest/

You can also use of the TRECQuery class to get the content of the tags. `pt.io.read_topics()` can be used for file reading files.  The underlying code is https://github.com/terrier-org/pyterrier/blob/master/pyterrier/io.py#L179

I'm not sure how that will deal with your special characters. Maths retrieval is a fairly specialised area of IR.

**Comment by wpertsch** [comment]
Ok everything works now. `pt.io.read_topics()` was what I was looking for!
I know Math retrieval is its own area, but I am building a baseline without retrieval in the latex-formulas. The problem was the Latex-code I that gave me problems querying.

Thank you so much for your patience, I learned a lot.

**Comment by cmacdonald** [comment]
Good to hear, thanks for the feedback!
