### ISSUE TITLE
 Jelinek-Mercer and dirichlet smoothing

### ISSUE THREAD

**Issue by Fatima-Haouari** [terrier-org/pyterrier#175]
Hi,
Are Jelinek-Mercer and dirichlet smoothing supported by PyTerrier?

**Comment by cmacdonald** [comment]
Hi @Fatima-Haouari,

BatchRetrieve, which uses Terrier's backend, supports all Terrier retrieval models - see full listing at http://terrier.org/docs/current/javadoc/org/terrier/matching/models/package-summary.html. IIRC Hiemstra_LM corresponds to Jelinek Mercer smoothing.

Documentation discussing choice of weighting model in PyTerrier is here: https://pyterrier.readthedocs.io/en/latest/terrier-retrieval.html

**Comment by Fatima-Haouari** [comment]
Thanks a lot for quick response @cmacdonald 
Could you please advise if there is a way to update the mu parameter when using the DirichletLM model? as by looking at the BatchRetrieve I can not figure out how this can be done?

**Comment by cmacdonald** [comment]
`pt.BatchRetrieve(index, wmodel='DirichletLM', controls={'c' : 1000})`

For very historical reasons in Terrier, the parameter is called 'c'. One day I will fix this!

**Comment by Fatima-Haouari** [comment]
Thanks a lot @cmacdonald

**Comment by Fatima-Haouari** [comment]
Can I ask how to update lambda parameter for Hiemstra_LM @cmacdonald ?

**Comment by cmacdonald** [comment]
Exactly the same way - the c control.

**Comment by Fatima-Haouari** [comment]
I really appreciate your quick response @cmacdonald
