### ISSUE TITLE
Evaluating empty resultset

### ISSUE THREAD

**Issue by cmacdonald** [terrier-org/pyterrier#176]
**Describe the bug**

When the resultset returned by a transformer is empty, the error message from ir_measures can vary depending on the provider.

**Expected behavior**
Perhaps a more clear PyTerrier error message

**Documentation and Issues**
 - [x] I have checked the [PyTerrier documentation](https://pyterrier.readthedocs.io/en/latest/) for relevant content
 - [x] I have checked for previous relevant [PyTerrier issues](https://github.com/terrier-org/pyterrier/issues)

**Comment by seanmacavaney** [comment]
This is related to the problem of basing the metrics on the:
 - Number topics in the result set (what's done now)
 - Union of topics in the result set and qrels
 - Intersection of topics in the result set and qrels
 - Number of topics passed into Experiment

(related to the [-c option issue in ir-measures](https://github.com/terrierteam/ir_measures/issues/2))

**Comment by cmacdonald** [comment]
In this case it was partly a simpler problem - transformer returned ZERO results for all queries.

**Comment by seanmacavaney** [comment]
Seems like ir-measures should handle this better, or it'll be unclear what error to catch in pyterrier. Then we can see how clear the errors are on the pyterrier side.

**Comment by cmacdonald** [comment]
I have added checks for empty result sets, which pt.Experiment and friends will refuse to evaluate. This seems the most straightforward resolution.

**Comment by seanmacavaney** [comment]
I'm still keen to get [this ir_measures PR out](https://github.com/terrierteam/ir_measures/pull/17), as I feel it is the correct (and least dangerous!) behaviour. If you're uncomfortable with the accompanying proposed pyterrier changes, perhaps let's consider freezing the ir_measures version in pyterrier for now?

**Comment by cmacdonald** [comment]
Yes we can freeze irm. I promise to get back to the pyterrier proposed changes.
