### ISSUE TITLE
Addititional dataset.get_topicsqrels() to make pt.Experiment faster to write

### ISSUE THREAD

**Issue by cmacdonald** [terrier-org/pyterrier#185]
**Is your feature request related to a problem? Please describe.**

Its frustrating writing dataset twice in pt.Experiment(), as we almost always getting the topics and qrels from the same 

```python
pt.Experiment(
 ...,
 dataset.get_topics(),
 dataset.get_qrels(),
...
)
```

**Describe the solution you'd like**

```python
pt.Experiment(
 ...,
 *dataset.get_topicsqrels(),
...
)
```

Implementation:

```python
class Dataset:
  def get_topicsqrels(self, *args, **kwargs):
    return (
      self.get_topics(*args, **kwargs),
      self.get_qrels(*args, **kwargs)
    )
```
**Describe alternatives you've considered**

Not using the * notation would be preferable, but this would require a more significant API change to pt.Experiment(). This is just an additional default method in dataset.

**Comment by seanmacavaney** [comment]
I suppose just passing in the dataset object itself isn't feasible, as one often needs to specify the variant?

(Would also require a more significant API change)

**Comment by cmacdonald** [comment]
> I suppose just passing in the dataset object itself isn't feasible, as one often needs to specify the variant?

Correct. And there are still cases where it useful to operate in terms of dataframes.

Other alternatives? - factory method, ugh, cant see how that would work here.

**Comment by seanmacavaney** [comment]
`get_topicsqrels` seems generally like an easy fix. Won't always work, as sometimes the variant is different between the topics and qrels (e.g., variant is used in irds datasets to choose which query field, which doesn't apply to qrels), but still seems like a good solution for most cases.

**Comment by cmacdonald** [comment]
Documentation removed. Reopening to revert change at a later date.

**Comment by cmacdonald** [comment]
Reverted ec17d50ac4af6b311dc970bc33343ea75ec7bcd8, now closing.
