### ISSUE TITLE
Global properties for BatchRetrieve

### ISSUE THREAD

**Issue by seanmacavaney** [terrier-org/pyterrier#188]
**Describe the bug**

It seems that when building multiple BatchRetrieve objects, only the properties from the newest one are applied. E.g., if I do:

```python
bm25_nostem = pt.BatchRetrieve(index_nostem, wmodel='BM25', verbose=True, properties={
    'tokeniser': 'UTFTokeniser',
    'termpipelines': '',
})
bm25_stem = pt.BatchRetrieve(index_stem, wmodel='BM25', verbose=True, properties={
    'tokeniser': 'UTFTokeniser',
    'termpipelines': 'SpanishSnowballStemmer',
})
```

`termpipelines=SpanishSnowballStemmer` is applied to both retrievers.

**To Reproduce**
1. Which index: E.g., any two indices that used different termpipelines when constructed
2. Which retrieval: Observed with BM25
3. What pipeline: BatchRetrieve

**Expected behavior**

The properties should be applied to the corresponding retrievers only.

**Documentation and Issues**
 - [x] I have checked the [PyTerrier documentation](https://pyterrier.readthedocs.io/en/latest/) for relevant content
 - [x] I have checked for previous relevant [PyTerrier issues](https://github.com/terrier-org/pyterrier/issues)

**Additional context**
Observed when conducting experiments on `irds:wikir/es13k/test`, but this behavior seems like it would happen regardless of language.

**Comment by cmacdonald** [comment]
20 years of technical debt around a global configuration state... 👎 

I think the workaround is if you start using the bm25_nostem before instantiating  bm25_stem, the problem goes away. 

Stemming variations are the most common places where this can arise for BatchRetrieve. There may be other cases for FeaturesBatchRetrieve 

The upstream issue is https://github.com/terrier-org/terrier-core/issues/122

**Comment by cmacdonald** [comment]
@seanmacavaney when you have a chance, could you review https://github.com/terrier-org/terrier-core/pull/181

**Comment by cmacdonald** [comment]
So I think this is now addressed, and the notebooks could be updated. Two points:
 - I dont think the tokeniser property needs to be adjusted during retrieval?
 - termpipelines are identified automatically from the index, and can be overridden by controls.

**Comment by cmacdonald** [comment]
notebook now updated.
