### ISSUE TITLE
Expanded query have some misspelled words. Does RM3 have lemmatization someewhere?

### ISSUE THREAD

**Issue by deepkshikha** [terrier-org/pyterrier#190]
I used RM3 for query expansion though some of the words in the expanded query generated are incorrect. I have no lemmatization in the data pipeline like some examples below.

Given: 
    distinctions address number. 
Expanded
    frameless black hing instal elit shower matt distinct address clear number glass.

Given:
      hand soap dispenser
Expanded:
      soap hand chrome dispens capac countertop lotion mount

**Comment by cmacdonald** [comment]
Those are stemmed forms. Terrier applies Porter stemming by default.

Sent from my iPhone

On 17 Jun 2021, at 21:14, Deepshikha ***@***.***> wrote:

﻿

I used RM3 for query expansion though some of the words in the expanded query generated are incorrect. I have no lemmatization in the data pipeline like some examples below.

Given:
distinctions address number.
Expanded
frameless black hing instal elit shower matt distinct address clear number glass.

Given:
hand soap dispenser
Expanded:
soap hand chrome dispens capac countertop lotion mount

**Comment by deepkshikha** [comment]
Is there a way to remove or ignore that???

**Comment by cmacdonald** [comment]
Well stemming is normally effective - see any IR textbook. There are examples in the pyterrier documentation on indexing.

**Comment by deepkshikha** [comment]
It is effective but for the use case, it's not. So was looking away ignore or set False for stemming parrameterr?

**Comment by cmacdonald** [comment]
You need to index without stemming.
https://pyterrier.readthedocs.io/en/latest/terrier-indexing.html#indexing-configuration
shows how to create an index without stemming and stopword removal.

Similarly, for retrieval you need to `pt.BatchRetrieve(..., properties={"termpipelines" : ""})`. I cannot recall off hand how to adjust RM3.

**Comment by deepkshikha** [comment]
import pandas as pd
pt.DFIndexer.setProperty("termpipelines=Stopwords", " ") is this the right way??

I cannot recall off hand how to adjust RM3. : If you could point something for this that would be wonderful.

**Comment by cmacdonald** [comment]
```python
dfindexer = pt.DFIndexer(...)
dfindexer.setProperty("termpipelines", "Stopwords") 
```

**Comment by cmacdonald** [comment]
Similarly, `pt.rewrite.RM3(..., properties={"termpipelines" : "Stopwords"})`

As properties are globals, and there could be some unintended side-effects, I would strongly recommend running this experiment in a separate notebook from any experiments using a stemmed index.
