### ISSUE TITLE
How to tune weightmodels

### ISSUE THREAD

**Issue by wpertsch** [terrier-org/pyterrier#192]
I am experimenting with different weighting-models and tried to tune some.
There are some things i dont understand:

1. It is possible to tune some models via controls={"c":"0.15"} and in some cases (bm25) i can controll other parameters via properties={"bm25.k_1": "0.2"}. I get that k_1 is used in the "Okapi BM25"-model, what is the c for?
2. I want to tune tf_idf. Is there a way experimenting with different weightings for the tf or the idf part? I can not finde anything in the Pyterror nor the Terrier Documentation.

Thank you

**Comment by cmacdonald** [comment]
Hi @wpertsch 

The naming of the main parameter of the weighting model as "c" is for historical reasons (Terrier started with DFR models, and their length normalisation parameter was called "c". We were discussing this recently, and will attempt to change this going forward.

1. I think BM25 can be tuned using controls rather than properties.

2. Our TF_IDF is essentially BM11, and can be tuned using the "c" control, which affects the "b" parameter in the source code: 
https://github.com/terrier-org/terrier-core/blob/5.x/modules/core/src/main/java/org/terrier/matching/models/TF_IDF.java. The k_1 parameter in TF_IDF is not exposed.

Craig

**Comment by wpertsch** [comment]
Thank you for your quick response!

1.  So in BM25(http://terrier.org/docs/current/javadoc/org/terrier/matching/models/BM25.html) the c is the b parameter and, like its written in the docs, "Terrier’s BM25 also responds to controls named “bm25.k_1” and “bm25.k_3”."  As I said I am experimenting with some models, and so far, plain TF_IDF is outperforming tuned (for the c parameter) BM25 by far. Is there a way to do some grid search to adjust the k_1 and k_3 or do I have to try different things?

2. Thank you, this is very helpful.

Wilhelm

**Comment by cmacdonald** [comment]
You can tune “bm25.k_1” and “bm25.k_3” just like the "c" in a gridsearch (#191 notwithstanding)

**Comment by wpertsch** [comment]
Yes thank you, my question was a bit vague.
The optimal c value for my system is 0.3, but this seems to me to be only a local optimum for the value c when k_1 and k_3 are set to default.
Is there a way to optimize all 3 parameters at the same time? 
Could something like this work:
```
BM25 = pt.BatchRetrieve(index, wmodel="BM25", controls={"c" : 0.75, "k_1" : 0.75, "k_3" : 0.75})
pt.GridSearch(
    BM25,
    {BM25 : {"c" : [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1 ], 
              "k_1" : [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1 ], 
              "k_3" : [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1 ]}}
    train_topics,
    train_qrels,
    "map")
```
Also, what does the c value mean which I create for BM25 preemptively?
```
BM25 = pt.BatchRetrieve(index, wmodel="BM25", controls={"c" : 0.75})
```

**Comment by cmacdonald** [comment]
this should work:
```python
BM25 = pt.BatchRetrieve(index, wmodel="BM25", controls={"c" : 0.75, "bm25.k_1" : 0.75, "bm25.k_3" : 0.75})
pt.GridSearch(
    BM25,
    {BM25 : {"c" : [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1 ], 
              "bm25.k_1" : [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1 ], 
              "bm25.k_3" : [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1 ]}}
    train_topics,
    train_qrels,
    "map")
```

> Also, what does the c value mean which I create for BM25 preemptively?

The implementation of GridScan/GridSearch are such that the parameter being varied must be present in the underlying transformer to begin with, either as an instance attribute, of in the case of BatchRetrieve, as a control or property.

**Comment by cmacdonald** [comment]
if you get this working, a PR to add this example to the documentation would be appreciated.

**Comment by wpertsch** [comment]
Sorry for the long delay, my PC needed a day to get this done.
Based on the default falues of k_1 and k_3 I made some educated guesses and my GridSearch looked like this:

```
BM25 = pt.BatchRetrieve(index, wmodel="BM25", controls={"c": 0.75, "bm25.k_1": 0.75, "bm25.k_3": 0.75})
rtr = pt.GridSearch(
      BM25,
      {BM25: {"c": [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8],
              "bm25.k_1": [0.3, 0.6, 0.9, 1.2, 1.4, 1.6, 2],
              "bm25.k_3": [0.5, 2, 4, 6, 8, 10, 12, 14, 20]}},


get_topics(),
get_qrels(),
"map")
```

The result was:
`Best map is 0.016205
  Best setting is ['BR(BM25) c=0.3', 'BR(BM25) bm25.k_1=1.2', 'BR(BM25) bm25.k_3=20']
   BR(BM25)`
which is kind of disenchanting. 
An earlier run, where I only manipulated the c value (and used default k_1 =1.2 and k_3 = 8) had almoust the same map:
`Best map is 0.016154
   Best setting is ['BR(BM25) c=0.3']`

I dont know what a PR is, but i would love to help.
Also sorry that my code is black and white, do you edit this by hand or is there some kind of a shortcut?

**Comment by cmacdonald** [comment]
Can you do an example with a GridScan rather than GridSearch - as that will give you the table of all possible values. We need to check that each parameter had the desired impact? You can do it on three parameter values each initially.

For code highlighting the trick is to add python after the opening three backticks. 

Yes, optimisations take a while. You can get a speedup by using `num_threads=2` as a kwarg to BatchRetrieve. We haven't found much advantage over 2 threads.

HTH

**Comment by wpertsch** [comment]
Ok i tested k_1 and k_3 isolated and they had close to no impact on the MAP:

     tran_0  tran_0_bm25.k_1       map
      0  BR(BM25)              0.6  0.015121
      1  BR(BM25)              0.8  0.014949
      2  BR(BM25)              1.0  0.014738
      3  BR(BM25)              1.2  0.014366
      4  BR(BM25)              1.4  0.014212
      5  BR(BM25)              1.6  0.013889


      tran_0  tran_0_bm25.k_3       map
      0  BR(BM25)               12  0.014358
      1  BR(BM25)               14  0.014380
      2  BR(BM25)               20  0.014371
      3  BR(BM25)               23  0.014363
      4  BR(BM25)               25  0.014364
      5  BR(BM25)               28  0.014380
      6  BR(BM25)               30  0.014378
      7  BR(BM25)               40  0.014463

I will do a GridScan of all 3 together again and keep you updated.

`num_threads=2` does wonders!

**Comment by cmacdonald** [comment]
K_1 concerns within-doc frequency absorption, while K_3 affects query term frequency absorption. If most of your queries and docs mostly have single occurrences, then these parameters won't have much impact.

**Comment by cmacdonald** [comment]
Anyway, glad it's all working. I will update the Gridscan documentation to show an example with k_1 and k_3

**Comment by wpertsch** [comment]
Ok. Thank you for your time and effort.
What is a PR?

**Comment by cmacdonald** [comment]
Pull request - a change to the pyterrier code or documentation that can be reviewed and merged. Questions such as yours often show that something needs to be clearer

**Comment by cmacdonald** [comment]
I have added an additional BM25 example based on your code to the documentation. Thanks for the suggestion @wpertsch.

**Comment by wpertsch** [comment]
Hello its me again.
I am currently working through the theoretical foundations of the models. I have 2 questions:

1. when calculating TF_IDF, the source code (https://github.com/terrier-org/terrier-core/blob/5.x/modules/core/src/main/java/org/terrier/matching/models/TF_IDF.java#L82) uses the 'keyfrequency'. As what can one understand these?
2. after long research to bm25 it was not possible for me to understand the occurrence of k_3. In all explanations k_1 is well explained but k_3 does not occur at all. Would it be possible to send me the article on which Terrier's bm25 is based?

**Comment by DankoPenko** [comment]
Hi!

How can i tune the "mu" parameter for DirichletLM? http://terrier.org/docs/current/javadoc/org/terrier/matching/models/DirichletLM.html#%3Cinit%3E()

And is there a way to see what controls can be tuned withing a specified models?

Thanks in advance!

**Comment by DankoPenko** [comment]
> Yes - you need currently to check the source code of the various weighting models. Controls were a later innovation than properties (which are JVM-wide globals, rather than per-query configurations). I can make an issue to document the controls in Terrier for the various weighting models?

this would be great, thanks :)
