### ISSUE TITLE
Indexing a corpus iterator fails

### ISSUE THREAD

**Issue by adambaker** [terrier-org/pyterrier#197]
**Describe the bug**
I'm just trying to index the orcas data set to try experimenting with it, so following the examples I tried:
```python
In [7]: orcas = pt.get_dataset('irds:msmarco-document/orcas')
In [8]: index = pt.IndexFactory.of(pt.TRECCollectionIndexer("./orcas-index").index(orcas.get_corpus_iter()))
[INFO] [starting] building docstore
docs_iter: 3213835it [32:06, 1667.95it/s]
[INFO] [finished] docs_iter: [32:06] [3213835it] [1667.95it/s]
[INFO] [finished] building docstore [32:07]
msmarco-document/orcas documents:   0%|                                                    | 0/3213835 [00:00<?, ?it/s]---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-8-4a64dbfc7094> in <module>
----> 1 index = pt.IndexFactory.of(pt.TRECCollectionIndexer("./orcas-index").index(orcas.get_corpus_iter()))

~/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pyterrier/index.py in index(self, files_path)
    776         self.checkIndexExists()
    777         index = self.createIndexer()
--> 778         asList = createAsList(files_path)
    779
    780         _TaggedDocumentSetup(self.meta, self.meta_tags)

~/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pyterrier/index.py in createAsList(files_path)
    220     elif isinstance(files_path, list):
    221         asList = Arrays.asList(*files_path)
--> 222     return asList
    223
    224 # Using enum class create enumerations

UnboundLocalError: local variable 'asList' referenced before assignment
```

**Expected behavior**
I expected it to create an index with the orcas documents.

**Documentation and Issues**
 - [x] I have checked the [PyTerrier documentation](https://pyterrier.readthedocs.io/en/latest/) for relevant content
 - [x] I have checked for previous relevant [PyTerrier issues](https://github.com/terrier-org/pyterrier/issues)

**Additional context**

I went into the library installation inside my site-packages to print the data causing the issue, here: https://github.com/terrier-org/pyterrier/blob/master/pyterrier/index.py#L212-L222
and added an else condition to the type checks you are performing in `createAsList` that just dose
```python
raise ValueError(f"{files_path}: {type(files_path)} must be a list or str")
```
Which, when I tried to index orcas again, said
```
ValueError: <pyterrier.datasets.GeneratorLen object at 0x7f7ce5fe7dd0>: <class 'pyterrier.datasets.GeneratorLen'> must be a list or str
```

Also I should note that the type annotation on `createAsList`'s argument doesn't seem to agree with the body! It looks like the sig should be
```python
def createAsList(files_path: typing.Union[str, List[str]]): ...
```

**Comment by adambaker** [comment]
The examples I saw used `get_corpus` on the dataset instead of `get_corpus_iter`, but when I try `get_corpus` it says
```
NotImplementedError: IRDSDataset doesn't support get_corpus; use get_corpus_iter instead
```
This error message comes from pyterrier code, not from one of its dependencies, so it seems like a bug that it doesn't work.

**Comment by seanmacavaney** [comment]
Hi @adambaker,

I think you're looking for [`IterDictIndexer`](https://pyterrier.readthedocs.io/en/latest/terrier-indexing.html#iterdictindexer), which is used for indexing the output of `get_corpus_iter`. (`TRECCollectionIndexer` is used when you have TREC-formatted input files.) The following code works for me:

```python
dataset = pt.get_dataset('irds:msmarco-document/orcas')
indexer = pt.IterDictIndexer('./orcas-index')
index_ref = indexer.index(dataset.get_corpus_iter(), fields=['title', 'body'])
```

This code was based on the example code [on this page](https://ir-datasets.com/master/msmarco-document.html#msmarco-document/orcas) under docs > PyTerrier.

Regarding the `NotImplementedError` on `IRDSDataset` -- this is by design. `IRDSDataset` doesn't provide file paths for the corpus; the source files can be in a variety of formats, so the path itself is not particularly useful. Instead, it only provides an iterable over the documents. The exception from `get_corpus` can probably be improved to clear up confusion.

 \- sean

**Comment by adambaker** [comment]
Oh my. I never noticed the PyTerrier tab in the `ir_datasets` documentation. Thank you @seanmacavaney. That seems to be working.

You might want to fix the type or simplify the body of `createAsList` but that is not a public facing issue so I have no issue and I will close this one.

**Comment by cmacdonald** [comment]
> You might want to fix the type or simplify the body of createAsList but that is not a public facing issue so I have no issue and I will close this one.

Thanks, I can give a look at this.

**Comment by cmacdonald** [comment]
Thank you for suggestions, I have addressed this.
