### ISSUE TITLE
Query biased document summary in PyTerrier

### ISSUE THREAD

**Issue by adambaker** [terrier-org/pyterrier#205]
I'm trying to extract text snippets for a search results page. I've found the documentation page for running terrier in a JSP, which describes [some configuration for snippet extraction](https://github.com/terrier-org/terrier-core/blob/5.x/doc/terrier_http.md#using-the-web-based-interface).

I'm still not sure how to use this in pyterrier. It seems like `BatchRetrieve`'s `properties` or `control` parameters might be necessary to pass the required configuration, but then it's not clear to me how to get the query biased summary from the result set. Is there a way to do this with PyTerrier?

Thanks!

**Comment by cmacdonald** [comment]
Hi adam,

The query-biased summariser in Terrier is that great. What about just breaking the text of the retrieved documents into sentences, and passing them through another text scoring ranking pipeline?

Craig

**Comment by cmacdonald** [comment]
Adam, there is an draft PR for PyTerrier query biased summarisation at https://github.com/terrier-org/pyterrier/pull/223. We're not planning to merge for this week's PyT release, but it might be of interest.

**Comment by cmacdonald** [comment]
The corresponding PR has been merged - documentation at https://pyterrier.readthedocs.io/en/latest/text.html#query-biased-summarisation-snippets.
