### ISSUE TITLE
Understanding the PyTerrier Models

### ISSUE THREAD

**Issue by wpertsch** [terrier-org/pyterrier#206]
I am currently working through the theoretical foundations of the models. I have 2 questions:

1. when calculating TF_IDF, the source code (https://github.com/terrier-org/terrier-core/blob/5.x/modules/core/src/main/java/org/terrier/matching/models/TF_IDF.java#L82) uses the 'keyfrequency'. As what can one understand these?
2. after long research to bm25 it was not possible for me to understand the occurrence of k_3. In all explanations k_1 is well explained but k_3 does not occur at all. Would it be possible to send me the article on which Terrier's bm25 is based?

**Comment by cmacdonald** [comment]
keyFrequency is the frequency of the query term in the query. It is typically one, but could be >1 if a query term is repeated. When pseudo-relevance feedback is applied, weights are typically floats.

k_3 has the same role as k_1, but applied absorption to the query term frequencies. Jimmy Lin's ECIR paper says that "The original [BM25] publication adds scoring components with constants k2 and k3 that are rarely used. https://link.springer.com/chapter/10.1007/978-3-030-45442-5_4

**Comment by cmacdonald** [comment]
@wpertsch are these explanations OK, can I close this issue?

**Comment by wpertsch** [comment]
Yes, pardon
