### ISSUE TITLE
Problems with documents retrieval

### ISSUE THREAD

**Issue by somnath-banerjee** [terrier-org/pyterrier#210]
I've indexed 6518 documents using DFIndexer. The dataframe has 2 columns: docno and text. 
For indexing, I used:     
        indexer = pt.DFIndexer(pt_index_path, overwrite=False, verbose=True, Threads=8)
        index_ref = indexer.index(df_docs["text"], df_docs)

But while I'm retrieving the results using bm25 (_bm25 = pt.BatchRetrieve(index, wmodel="BM25",controls={"c" : 0.75}, properties={"bm25.k_1": "0.2"}; bm25.transform(queries)_), I am only getting 38 documents for 1st and 2nd queries, 45 for the third, and 3 for the 4th...
I also tried: _pt.ApplicationSetup.setProperty("matching.retrieved_set_size", "1000")_ but not succeed. 

Here is my data.propertis file:
index.document-factory.parameter_values=
index.meta-inputstream.parameter_types=org.terrier.structures.IndexOnDisk,java.lang.String
index.lexicon.termids=fileinmem
index.meta-inputstream.class=org.terrier.structures.ZstdCompressedMetaIndex$InputStream
index.inverted-inputstream.class=org.terrier.structures.bit.BitPostingIndexInputStream
index.lexicon-valuefactory.class=org.terrier.structures.BasicLexiconEntry$Factory
index.document.class=org.terrier.structures.FSADocumentIndex
index.lexicon.class=org.terrier.structures.FSOMapFileLexicon
index.lexicon-inputstream.parameter_values=structureName,index
num.Documents=6518
index.lexicon-entry-inputstream.class=org.terrier.structures.FSOMapFileLexicon$MapFileLexiconEntryIterator
index.meta.class=org.terrier.structures.ZstdCompressedMetaIndex
index.inverted-inputstream.parameter_values=index,structureName,lexicon-entry-inputstream,org.terrier.structures.postings.bit.BasicIterablePosting
index.lexicon.bsearchshortcut=charmap
index.lexicon-inputstream.parameter_types=java.lang.String,org.terrier.structures.IndexOnDisk
index.lexicon-keyfactory.parameter_values=${max.term.length}
num.Tokens=6836266
index.direct.class=org.terrier.structures.bit.BitPostingIndex
index.lexicon-inputstream.class=org.terrier.structures.FSOMapFileLexicon$MapFileLexiconIterator
index.lexicon-valuefactory.parameter_types=
index.document.parameter_types=org.terrier.structures.IndexOnDisk,java.lang.String
index.lexicon-entry-inputstream.parameter_values=structureName,index
index.inverted.blocks.max=0
index.meta.entry-length=109
index.meta.value-lengths=36
termpipelines=Stopwords,PorterStemmer
max.term.length=20
index.direct-inputstream.parameter_types=org.terrier.structures.IndexOnDisk,java.lang.String,java.util.Iterator,java.lang.Class
index.inverted-inputstream.parameter_types=org.terrier.structures.IndexOnDisk,java.lang.String,java.util.Iterator,java.lang.Class
index.direct.fields.count=0
index.lexicon-keyfactory.class=org.terrier.structures.seralization.FixedSizeTextFactory
index.meta.parameter_types=org.terrier.structures.IndexOnDisk,java.lang.String
index.lexicon-entry-inputstream.parameter_types=java.lang.String,org.terrier.structures.IndexOnDisk
index.inverted.class=org.terrier.structures.bit.BitPostingIndex
index.document-factory.parameter_types=
index.meta.value-sorted=false
index.document-inputstream.parameter_types=org.terrier.structures.IndexOnDisk,java.lang.String
index.direct.blocks=0
index.direct.blocks.max=0
index.inverted.parameter_types=org.terrier.structures.IndexOnDisk,java.lang.String,java.lang.Class
index.meta.entries=6518
num.Pointers=3173556
index.inverted.blocks=0
index.terrier.version=5.5
index.meta.reverse-key-names=
index.lexicon.parameter_types=java.lang.String,org.terrier.structures.IndexOnDisk
index.meta.parameter_values=index,structureName
num.Terms=87838
index.inverted.fields.names=
index.direct-inputstream.parameter_values=index,structureName,document-inputstream,org.terrier.structures.postings.bit.BasicIterablePosting
index.direct.parameter_types=org.terrier.structures.IndexOnDisk,java.lang.String,java.lang.Class
index.direct-inputstream.class=org.terrier.structures.bit.BitPostingIndexInputStream
index.document.parameter_values=index,structureName
index.inverted.fields.count=0
index.document-inputstream.parameter_values=index,structureName
index.meta.index-source=fileinmem
index.meta-inputstream.parameter_values=index,structureName
index.meta.key-names=docno
index.lexicon-keyfactory.parameter_types=java.lang.String
index.document-inputstream.class=org.terrier.structures.FSADocumentIndex$FSADocumentIndexIterator
index.lexicon.parameter_values=structureName,index
index.lexicon-valuefactory.parameter_values=
index.direct.fields.names=
index.created=1627369548147
index.document-factory.class=org.terrier.structures.BasicDocumentIndexEntry$Factory
index.direct.parameter_values=index,structureName,org.terrier.structures.postings.bit.BasicIterablePosting
index.inverted.parameter_values=index,structureName,org.terrier.structures.postings.bit.BasicIterablePosting
index.meta.data-source=fileinmem
How could I retrieve 1000 documents as result for each query? Please help

**Comment by cmacdonald** [comment]
If you are only getting a few documents for each query, the chances are that only a few documents actually match each query. You can give a look at the lexicon for those terms?

**Comment by cmacdonald** [comment]
Any news?

**Comment by somnath-banerjee** [comment]
Dear Craig Macdonald,

I checked the documents and found that around 1000 documents contain the
third term of the query and still it retrieves fewer documents. It is
strange. I also tried IterDictIndexer for indexing and got the same
results. I used the default stemming. Due to other commitments, I did not
manage to perform other analyses of the documents.
If you want I could share the documents and code, and I really would like
to know the cause of that strange outcome.  Perhaps, I am missing something.

Thanks & Regards,
Somnath


ᐧ

**Comment by cmacdonald** [comment]
Example documents, esp. in a Colab notebook, would make it very easy for me to help you.

**Comment by somnath-banerjee** [comment]
Hi Craig,

Thanks for your concern and time.

Here, I'm sharing the folder with you which contains all the stuff for the
experiments.

https://drive.google.com/drive/folders/1wIaQai1iuSwhChF0kkfJxWfxJqDr5g-8?usp=sharing

Colab file:
https://colab.research.google.com/drive/16y7KJn8QsjhWr3tIYpkFhr5j0oYY-8bh?usp=sharing

Hope to hear from you soon!

Thanks & Regards,
Somnath
ᐧ

**Comment by cmacdonald** [comment]
Hi Somnath,

So @seanmacavaney gave a quick look at this before I had a chance. He spotted that your queries contain "covid-19". Terrier will treat this as finding documents containing 'covid' and NOT containing '19'.

You should escape your queries. If you use pt.io.read_topics() to read your topics for you, it will fix this.

HTH

Craig

**Comment by somnath-banerjee** [comment]
Dear Craig,

I read the topics using pt.io.read_topics() and the problem is solved.

Thanks a lot @seanmacavaney <https://github.com/seanmacavaney> and you for
your effort and time.

Kind regards,
Somnath
ᐧ
