### ISSUE TITLE
Using PyTerrier when not connected to Internet

### ISSUE THREAD

**Issue by shuishen112** [terrier-org/pyterrier#224]
import pyterrier as pt

pt.init()

when I init the pyterrier, it has to make the Internet connected, I don't think it is reasonable. Because in some running situations, the network may doesn't work.

**Comment by cmacdonald** [comment]
Hi @shuishen112. Thanks for the fair comment. Yes, this is the envisaged usage at present. In situations where the jar files are already available. This is a problem that we were aware that we would have to solve soon. 

How about `pt.init(offline=True)`

Craig

**Comment by shuishen112** [comment]
Thanks, I have rewritten the source code and it can up run offline If we add the version and helper_version in init().

For example:
pt.init(version = 5.5, helper_version = "0.0.6")

Do I need to push a request?

**Comment by cmacdonald** [comment]
PR would be great.

**Comment by shuishen112** [comment]
I have added a pull request and I hope it will be helpful.

**Comment by cmacdonald** [comment]
Thanks shuishen. We'll review, but it may be next week.

I'm wondering how we can unit test this on a Github Action - perhaps by by monkey-patching the requests/wget objects?

**Comment by seanmacavaney** [comment]
It might be nice if PyTerrier could automatically fall back on the latest library version if the maven lookup fails and a prior version was already downloaded.
