### ISSUE TITLE
Is there a way to process text in memory/not on disk?

### ISSUE THREAD

**Issue by jackweitze** [terrier-org/pyterrier#252]
pyterrier.io.read_topics has a nice interface for processing queries on disk.

But what if I have text data in memory, e.g. a string?

`pyterrer.io.process_topics(["query one", ...])`

It's not super clear how to access terrier's underlying text processing for tokenization and stemming, so having a function which goes through the same pipeline as read_topics would be helpful for testing.

Thanks!

**Comment by cmacdonald** [comment]
pt.new.queries() will construct a queries dataframe.

Stemming is assumed to happen at the level of the transformer - e.g. at the Terrier stage. pt.io.read_topics() does indeed do some light tokenisation, to remove punctuation etc that will break Terrier's query parser. I will add a snippet for showing how to access these.

**Comment by cmacdonald** [comment]
In #252, @seanmacavaney gave a snippet of how to deal with this:
https://github.com/terrier-org/pyterrier/issues/253#issuecomment-996160987
