### ISSUE TITLE
planned public API for transformers

### ISSUE THREAD

**Issue by cmacdonald** [terrier-org/pyterrier#271]
- Change all occurrences of `pt.transformer.TransformerBase` to `pt.Transformer`
- Deprecate `pt.transformer.TransformerBase`
- Add other Transformer sub-classes: indexing and fitting.

**Comment by cmacdonald** [comment]
Can these classes should be available before pt.init()

**Comment by seanmacavaney** [comment]
It would nice if everything that wasn't pyjnius-dependent was available before `pt.init()`

**Comment by cmacdonald** [comment]
Or at least more stuff. In transformer.py, `setup_rewrites()` is where the dependence on batchretrieve.py arises - that could be moved to an init method in batchretrieve.py
