### ISSUE TITLE
Craft an Index with previously given Tokens

### ISSUE THREAD

**Issue by wpertsch** [terrier-org/pyterrier#281]
For a project, the goal is to create an index from filtered code. A conventional utf-8 tokenizer would be ineffective because it would not leave much of the corpus.
But since tokens are already given for each document, it would be a very big advantage to create an index directly from them. Is there a way to do this?

**Comment by cmacdonald** [comment]
Hi

So I'm assuming this discussion only applies to the Terrier backend. 

So for Terrier, at indexing time there is an [IdentityTokeniser](https://github.com/terrier-org/terrier-core/blob/5.x/modules/core/src/main/java/org/terrier/indexing/tokenisation/IdentityTokeniser.java) - thats just reads all it can into a String. I guess you need one that just splits on single space?

For querying, you would need to encode tokens using `#base64` notation.

**Comment by cmacdonald** [comment]
@wpertsch you can see something in this direction at https://github.com/cmacdonald/pyt_splade. More work is ongoing

**Comment by cmacdonald** [comment]
Now addressed for #328
