### ISSUE TITLE
LTR fit memory usage

### ISSUE THREAD

**Issue by MonicaLeone** [terrier-org/pyterrier#283]
**Describe the bug**
When I try to run a L2R model (in particular a SKLearn regressor) with additional document features on Colab, after train for 30 minutes it crashes and gives me the following error:
warning:root:kernel e2569308-715f-410a-975c-3d43f348e7e4 restarted colab

I am just running this code:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators=400)
rf_pipe = pipeline >> pt.ltr.apply_learned_model(rf)
rf_pipe.fit(train_topics_100.head(100), train_qrel_100.head(100))

with 100 queries. 

It seems that colab is crushing because all the RAM has been used, but how can I avoid this?

**Comment by cmacdonald** [comment]
Hi Monica,

A few ideas:
 - try using less trees?
 - use less topics
 - use less document for each query, i.e. `rf_pipe = (pipeline % 20) >> pt.ltr.apply_learned_model(rf)`
 - I wonder if you have extra columns in your pipeline (e.g. document text) that you could drop come the feature stage?

See also https://stackoverflow.com/a/20952691 for how to train RF regressors on different data portions

NB: taking head on the training qrels may not equate to the head on the training topic. There is a left join between training topics and qrels inside pt.ltr.apply_learned_model, so I would remove head from train_qrel.

**Comment by cmacdonald** [comment]
PR https://github.com/terrier-org/pyterrier/pull/284 may reduce memory consumption a little.

But for me, the overriding concern will be the number of documents being re-ranked, and using, e.g. `%20`, will definitely help you.

You might also try a different learner.
