### ISSUE TITLE
How to apply weights to fields using Pyterrier for BM25F model.

### ISSUE THREAD

**Issue by soydanielle** [terrier-org/pyterrier#294]
Hi, I have been trying to find somewhere in the documentation on how to apply weights to fields as I'm using BM25F for a dataset. Would you be able to let me know if there's a function on Pyterrier in which can be used.

**Comment by cmacdonald** [comment]
Thanks for your good question. I agree that this is missing from the documentation, and indeed, I had to patch Terrier core to make this work properly.

Here is an example for an index that has 2 fields.

```python

# this is required to use the latest github version of Terrier
pt.init(version='snapshot')

# <snip> load your index

# check your index has fields
print(index.getCollectionStatistics().toString())

# instantiate BatchRetrieve for BM25F
# you can also introduce c.0, c.1 etc to facilitate tuning the per-field normalisation parameters
bm25f = pt.BatchRetrieve(index, wmodel='BM25F', controls={'w.0' : 1, 'w.1' : 1}, verbose=True)
pt.GridScan(
    bm25f, 
    # you can name more parameters here and their values to try
    {bm25f: {'w.0' : [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1 ]}},
    dataset.get_topics('training').head(4),
    dataset.get_qrels('training'),
    ['map']
)
# GridScan returns a table of MAP values for all attempted parameter settings
```

**Comment by cmacdonald** [comment]
I have opened a PR with improved documentation  - see https://github.com/terrier-org/pyterrier/pull/296 - perhaps you could post some feedback - would this have addressed your question @soydanielle ?

**Comment by soydanielle** [comment]
Okay, yes it did help! Thanks so much. 
I'll post some feedback soon.😁

**Comment by cmacdonald** [comment]
Nothing heard, documentation merged.
