### ISSUE TITLE
How to add / remove documents from index on the fly

### ISSUE THREAD

**Issue by joelrorseth** [terrier-org/pyterrier#297]
Hi, first of all, thanks for this great tool. I am wondering if there is any way to efficiently add (and remove) a document to (from) an index that has already been built, without recreating the entire dataset and index?

For context, I am using PyTerrier to create an explainability tool, to explain document ranking models. To create the explanation for a given document (w.r.t. its score / rank), I need to evaluate the score / rank of many perturbed copies of this document. I'm hoping to replace this given document (in the index) with a perturbed version of itself, N times, each time regenerating an independent ranking.

Not sure if this is helpful, but this is how I am creating and loading MSMARCO using PyTerrier:

```
pt.init()
INDEX_PATH = './indices/msmarco-document'
dataset = pt.get_dataset('irds:msmarco-document/dev')

# Create index
#indexer = pt.IterDictIndexer(INDEX_PATH)
#index_ref = indexer.index(dataset.get_corpus_iter(), fields=['url', 'title', 'body'])

# Load index
index_ref = pt.IndexRef.of(INDEX_PATH)
index = pt.IndexFactory.of(index_ref)

# TODO: Remove old document from index, add new document

# Obtain ranking
pipeline = pt.BatchRetrieve(index_ref, wmodel='BM25')
bm25_ranking = pipeline(dataset.get_topics())
```

I appreciate your help, thanks in advance!

**Comment by cmacdonald** [comment]
Hi Joel, thanks for your question. I'd suggest the easiest way to do this is to use pt.text.scorer().

This has the effect of creating a memory index and then executing the query on that. You can use the existing index as the background index, ie source for collection and term statistics.

This way you don't need to play with removing docs from indices etc.

Craig

**Comment by joelrorseth** [comment]
Hi Craig, thanks for the quick reply. This is exactly what I need, thanks again for your help! Closing this issue now, cheers!

Joel
