### ISSUE TITLE
Why the result of TREC-news dataset is 0?

### ISSUE THREAD

**Issue by shuishen112** [terrier-org/pyterrier#299]
I am trying to use pyterrier to index and search TREC-news datasets. When I follow the instructions here:https://ir-datasets.com/wapo.html. The MAP and NDCG score of the result is 0!. Here is my code:

`import pyterrier as pt
from pyterrier.measures import *
dataset = pt.get_dataset('irds:wapo/v2/trec-core-2018')
index_ref = pt.IndexRef.of('./indices/wapo_v2') # assumes you have already built an index
pipeline = pt.BatchRetrieve(index_ref, wmodel='BM25')

result = pt.Experiment(
    [pipeline],
    dataset.get_topics('title'),
    dataset.get_qrels(),
    [MAP, nDCG@20]
)
print(result)`
<img width="371" alt="image" src="https://user-images.githubusercontent.com/10068278/163717802-e6fd5234-9914-4e3b-b074-c34abb032f4a.png">

**Comment by cmacdonald** [comment]
I think perhaps the fields exported by irds don't match the indexer IterDictIndexer configuration. Was there any warnings made during indexing?

Can you print the index collection statistics?

Can you do a .search() on the batchretrieve object and see how if it retrieves anything?

**Comment by seanmacavaney** [comment]
Looks like the `docno` is being chopped off -- the default maximum length is 20, but docnos in `wapo/v2` are up to 36 characters.

Replacing:

```python
indexer = pt.IterDictIndexer("./indices/wapo_v2")
```

with

```python
indexer = pt.IterDictIndexer("./indices/wapo_v2", meta={'docno': 36})
```

Fixes the issue:

```python
result = pt.Experiment(
  [pipeline],
  dataset.get_topics('title'),
  dataset.get_qrels(),
  [MAP, nDCG@20]
)
print(result)
       name       AP   nDCG@20
0  BR(BM25)  0.19026  0.351261
```

I've written up an issue in the irds documentation repo to use the available metadata when generating the pyterrier indexing samples: https://github.com/seanmacavaney/ir-datasets.com/issues/3

NB: you may want to only index title and body fields -- not sure if URL, author, and kicker are useful for TREC CORE.

**Comment by shuishen112** [comment]
> 

Thanks. @seanmacavaney. You are right. How about the "irds:wapo/v2/trec-news-2019"? Here is my code:

`import pyterrier as pt
from pyterrier.measures import *

pt.init()
dataset = pt.get_dataset("irds:wapo/v2/trec-news-2019")
# Index wapo/v2

# indexer = pt.IterDictIndexer("./indices/wapo_v2", meta={"docno": 36})
# index_ref = indexer.index(
#     dataset.get_corpus_iter(),
#     fields=["title", "body"],
# )

# dataset = pt.get_dataset("irds:wapo/v2/trec-core-2018")
index_ref = pt.IndexRef.of(
    "./indices/wapo_v2"
)  # assumes you have already built an index

index = pt.IndexFactory.of(index_ref)
print(index.getCollectionStatistics().toString())


pipeline = pt.BatchRetrieve(index_ref, wmodel="BM25")


# (optionally other pipeline components)
result = pt.Experiment(
    [pipeline], dataset.get_topics('doc_id'), dataset.get_qrels(), [MAP, nDCG @ 20]
)

print(result)
`
There are a lot of empty query:

`       name   AP  nDCG@20
0  BR(BM25)  0.0      0.0`

But when I use:

`dataset.get_topics('url')`

I got:

'       name        AP   nDCG@20
0  BR(BM25)  0.032327  0.037214'.

Is it a correct result?

**Comment by cmacdonald** [comment]
> Looks like the `docno` is being chopped off -- the default maximum length is 20, but docnos in `wapo/v2` are up to 36 characters.

The indexer should have emitted a warning about this at indexing time.

**Comment by seanmacavaney** [comment]
> How about the "irds:wapo/v2/trec-news-2019"?

[TREC News](http://trec-news.org/) isn't an adhoc retrieval task like TREC Core. The main task is "background linking", where, given a document, the goal to rank documents that provide background information. Thus, the "topic" file just gives document IDs/URLs, and it's up to you to decide how to formulate a query for the task. I'm not sure what approach people normally take for this, but the [track overview paper](https://trec.nist.gov/pubs/trec27/papers/Overview-News.pdf) may be a good place to start.

-------------------------

> The indexer should have emitted a warning about this at indexing time.

I didn't get a warning in interactive python:
```python
Python 3.7.10 (default, Jun  4 2021, 14:48:32) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyterrier as pt
>>> pt.init()
PyTerrier 0.8.0 has loaded Terrier 5.6 (built by craigmacdonald on 2021-09-17 13:27)

No etc/terrier.properties, using terrier.default.properties for bootstrap configuration.
>>> dataset = pt.get_dataset("irds:wapo/v2/trec-news-2019")
>>> indexer = pt.IterDictIndexer("./indices/wapo_v2")
>>> index_ref = indexer.index(dataset.get_corpus_iter(), fields=["url", "title", "author", "kicker", "body"])
wapo/v2/trec-news-2019 documents: 100%|████████████| 595037/595037 [04:28<00:00, 2218.22it/s]
>>> pipeline = pt.BatchRetrieve(index_ref, wmodel='BM25')
...
```

(Or are you suggesting that we ought to add a warning?)

**Comment by seanmacavaney** [comment]
> I've written up an issue in the irds documentation repo to use the available metadata when generating the pyterrier indexing samples

Examples now fixed -- maximum length is included in samples when it exceeds the default maximum:

<img width="652" alt="image" src="https://user-images.githubusercontent.com/2607830/163807957-2b2f8b18-b37f-4096-812a-e3487653c492.png">

**Comment by cmacdonald** [comment]
> Examples now fixed 
Very good Sean!

> (Or are you suggesting that we ought to add a warning?)
I thought there was a warning. I will check.

**Comment by shuishen112** [comment]
aThanks. One more question. I think the result for trec-news-2019 is a little weird.

```

dataset = pt.get_dataset("irds:wapo/v2/trec-news-2019")
index_ref = pt.IndexRef.of(
    "./indices/wapo_v2"
)  # assumes you have already built an index
pipeline = pt.BatchRetrieve(index_ref, wmodel="BM25")
# (optionally other pipeline components)
result = pt.Experiment(
    [pipeline], dataset.get_topics("doc_id"), dataset.get_qrels(), [MAP, nDCG @ 20]
)

print(result)
```
The result is 
```
       name        AP   nDCG@20
0  BR(BM25)  0.000025  0.000082
```

**Comment by seanmacavaney** [comment]
Does this help?

> [TREC News](http://trec-news.org/) isn't an adhoc retrieval task like TREC Core. The main task is "background linking", where, given a document, the goal to rank documents that provide background information. Thus, the "topic" file just gives document IDs/URLs, and it's up to you to decide how to formulate a query for the task. I'm not sure what approach people normally take for this, but the [track overview paper](https://trec.nist.gov/pubs/trec27/papers/Overview-News.pdf) may be a good place to start.

**Comment by cmacdonald** [comment]
Closing as addressed in IRDS
