### ISSUE TITLE
KeyError for Experiment with perquery=True

### ISSUE THREAD

**Issue by Xiao0728** [terrier-org/pyterrier#30]
Hi Craig,

the Experiment object in `pipelines.py` has an error with the input `"perquery=Ture"`. The root cause might because evalMeasuresDict.keys() are qid, not eval_metrics, e.g, 'map' when `perquery='Ture`.

![image](https://user-images.githubusercontent.com/43675140/82927991-6f933900-9f79-11ea-80e5-4fa91cd737c0.png)

Thus, the lines
`evalMeasures = [evalMeasuresDict[m] for m in eval_metrics]` would be keyError.

Thanks,
Xiao

**Comment by cmacdonald** [comment]
Fixed. Thanks for the report Xiao.
