### ISSUE TITLE
Changing topics/qrels in Experiment with save_dir may lead to misunderstanding

### ISSUE THREAD

**Issue by albertoueda** [terrier-org/pyterrier#304]
**Is your feature request related to a problem? Please describe.**
The default value for `save_mode` is `reuse`. If we keep the names for the experiment runs but change the args for Experiment params (e.g., topics, qrels), we will keep getting the same results, because the files loaded will be the same. That can lead to misunderstanding to new users of PyTerrier, using variations of the same experiment but with the same run name. Not sure if that happens with caching too. 

e.g.,
```python
pt.Experiment( 
    [bm25, dph], 
    topics[:5], qrels, eval_metrics,
    names=['bm25', 'dph'],
    save_dir="./runs"
)

pt.Experiment( 
    [bm25, dph], 
    topics[:40], qrels, eval_metrics,
    names=['bm25', 'dph'],
    save_dir="./runs"
)
```
will return the same results. 

I'm not sure if it is a problem or is supposed to be this way, but it may lead to misunderstanding. 

**Describe the solution you'd like**
A warning in the code/documentation about that looks good.

**Describe alternatives you've considered**
- default for save_mode: `overwrite`, but it can be too aggressive.
- no save_mode, save_dir will always overwrite the results with the same name. The `reuse` can be delegated to caching. Same problem of aggressiveness.

**Comment by cmacdonald** [comment]
Should the save_dir activate a small file with experiment metadata, to ensure reproducibility?

**Comment by albertoueda** [comment]
> Should the save_dir activate a small file with experiment metadata, to ensure reproducibility?

I think it is a good idea. That made me think of a possible "label" parameter, where the user can register more detailed information about the generated run, via keywords or plain text. Currently, the name of the run (which is often intended to be short) is very important in this configuration of reusable runs.

**Comment by cmacdonald** [comment]
Looking back at this, I think there is an alternative option here. A new `save_mode` value of "error", which is the default.
"error" mode refuses to overwrite or reuse an existing file, but provides a useful message saying what should be done instead.

**Comment by cmacdonald** [comment]
PR #408 addresses this. Could you review please @albertoueda?
