### ISSUE TITLE
How to build multiple fields index and use multiple keywords to get query result?

### ISSUE THREAD

**Issue by Monoxide-Chen** [terrier-org/pyterrier#307]
Hi, if text format like this json:
```json
{
"docno": "xxx",
"text": "xxx",
"title":  "xxx",
"author": "xxx"
}
```
How can I use pyterrier to create Index for texts? And I want to do query using multiple keywords, just like:
```json
{"text":"use pyterrier", "title": "How to use terrier", "author": "Bill"}
```

**Comment by cmacdonald** [comment]
Use pt.IterDictIndexer

**Comment by Monoxide-Chen** [comment]
How to use multiple keywords for retrieval?

**Comment by cmacdonald** [comment]
Ah, is this is about retrieval across different fields?

**Comment by Monoxide-Chen** [comment]
Yeah, but I can't set fields using the function `Index()`

**Comment by Monoxide-Chen** [comment]
The following code can set different field 
```python
def data_doc_iter():
    for i in range(0, len): 
        docno, text, titile, author =  get_dataset(i)     
        yield {'docno':docno, 'text':text, 'title': title, 'author':author}

doc_iter = data_doc_iter()
indexer = pt.IterDictIndexer(index_path)
indexref = index.index(doc_iter, field = ['text','title','author'])
```
And how to use different field for searching?

**Comment by cmacdonald** [comment]
See https://github.com/terrier-org/terrier-core/blob/5.x/doc/querylanguage.md for examples of the Terrier query language including fields.

**Comment by Monoxide-Chen** [comment]
Thanks! Just use Query language like `"Bill .author terrier .title"` is ok.

**Comment by cmacdonald** [comment]
Author:bill under the normal query language. Otherwise you have to force it to matchops

**Comment by Monoxide-Chen** [comment]
I see `term1.title -- scores documents containing this single query term in the title.`  is a Matching Op Query Language. Should I use `#tag` or `#combine` ?

**Comment by cmacdonald** [comment]
Yes, using any #combine will force matchop language

**Comment by Monoxide-Chen** [comment]
If the weight of each field are fixed, can I set up before it query?

**Comment by cmacdonald** [comment]
What about using BM25F or PL2F models? Then you don't need to specify the field for each query terms.

**Comment by Monoxide-Chen** [comment]
Thank you for your answer! But using BM25F or PL2F models is not a good method to solve because these models costs too much time. My job is more about performance. I think `#combine` is better.
