### ISSUE TITLE
check PYTERRIER_HOME exists 

### ISSUE THREAD

**Issue by cmacdonald** [terrier-org/pyterrier#318]

**Comment by seanmacavaney** [comment]
Might be as simple as un-indenting these lines: https://github.com/terrier-org/pyterrier/blob/master/pyterrier/__init__.py#L101-L102

**Comment by seanmacavaney** [comment]
Also, while we're at it, can we allow the user to omit the trailing slash?

**Comment by cmacdonald** [comment]
do you recall why the trailing slash is needed? I cant see anything obvious in the code for setup_terrier, mavenresolver.py or datasets.py
