### ISSUE TITLE
Apply doc_score to batches of documents

### ISSUE THREAD

**Issue by JohnGiorgi** [terrier-org/pyterrier#321]
**Is your feature request related to a problem? Please describe.**

I am wondering if it is possible to apply the `doc_score` transformer in _batches_. The motivation is that this appears to be the primary interface for adding custom re-rankers, and many of these re-rankers will be neural language models whose inference speed can be dramatically increased by batching. Currently, the `fn` provided to `doc_score` is applied to each row of the dataframe independently.

**Describe the solution you'd like**

An argument, e.g. `batch_size` to the `doc_score` transformer that controls how many rows in the `pd.Series` object the provided `fn` receives.

**Describe alternatives you've considered**

- Approach 1: Add an argument `batch_size` to `doc_score`. This could be passed to `ApplyDocumentScoringTransformer`, which would be used in `transformer` to chunk the `inputRes` dataframe into `batch_size` chunks, provding each to `fn` in a loop and collecting the `scores`.
- Approach 2: Add an argument  to `doc_score`, say `all_rows`, which if positive passes the entire dataframe to `fn`. Batching would then be up to the `fn` implementation.

**Additional context**

I would be happy to open a PR if either approach seems promising, and this is a feature that would be welcome in the library. Approach 2 seems simpler and would allow the caller to implement batching however they want. Would look something like:

```python
import warnings
from pyterrier.apply import ApplyTransformerBase
from pyterrier.model import add_ranks

class ApplyDocumentScoringTransformer(ApplyTransformerBase):
    """
        Implements a transformer that can apply a function to perform document scoring. The supplied function 
        should take as input one row, and return a float for the score of the document.
        
        Usually accessed using pt.apply.doc_score()::
            def _score_fn(row):
                return float(row["url".count("/")])
            
            pipe = pt.BatchRetrieve(index) >> pt.apply.doc_score(_score_fn)
    """
    def __init__(self, fn,  *args, **kwargs):
        """
            Arguments:
             - fn (Callable): Takes as input a panda Series for a row representing that document, and returns the new float doument score 
        """
        super().__init__(fn, *args, **kwargs)
    
    def transform(self, inputRes, all_rows = False):
        fn = self.fn
        outputRes = inputRes.copy()
        if all_rows:
            if self.verbose:
                warnings.warn("Cannot provide progess when all_rows is True")
            outputRes["score"] = fn(outputRes)
        else:
            if self.verbose:
                tqdm.pandas(desc="pt.apply.doc_score", unit="d")
                outputRes["score"] = outputRes.progress_apply(fn, axis=1)
            else:
                outputRes["score"] = outputRes.apply(fn, axis=1)
        outputRes = add_ranks(outputRes)
        return outputRes
```

**Comment by cmacdonald** [comment]
Hi @JohnGiorgi in principle I am in favour of easier batching. The API should be:
`pt.apply.doc_score(_score_fn, batch_size=128)`

As, under the PyTerrier API, the transform() method cannot have more arguments (transform may be called by a concatenate) etc.

**Comment by cmacdonald** [comment]
Hi @JohnGiorgi  - could you give a look at PR #325 ?
