### ISSUE TITLE
Update Index

### ISSUE THREAD

**Issue by Watheq9** [terrier-org/pyterrier#329]
Hi @cmacdonald , 
I need to add new documents to an already-built index (I used IterDictIndexer to build it). 
Is there a way to update the index with the new documents without rebuilding the index again from scratch?
Please note that I need to update the index every now and then. So, it is very costly to re-index the whole collection with the new documents at every update.
I searched in the documentation [here](https://pyterrier.readthedocs.io) but didn't find what I wanted.

**Comment by cmacdonald** [comment]
Hi @Watheq9 

We dont document/expose the updatable indices of Terrier through the PyTerrier API, although they do exist.

You can create a new index with existing document, and `+` that together with the existing index, for comparable retrieval.

```python
index1 = pt.IndexFactory.of("./index1")
index2 = pt.IndexFactory.of("./index2")
comb_index = index1 + index2
br = pt.BatchRetrieve(comb_index)
```

HTH. 

Longer term I can see ways that we /could/ better support updatable indices within Terrier, but we dont have the bandwidth to address this.

**Comment by g-lopes** [comment]
> Hi @Watheq9
> 
> We dont document/expose the updatable indices of Terrier through the PyTerrier API, although they do exist.
> 
> You can create a new index with existing document, and `+` that together with the existing index, for comparable retrieval.
> 
> ```python
> index1 = pt.IndexFactory.of("./index1")
> index2 = pt.IndexFactory.of("./index2")
> comb_index = index1 + index2
> br = pt.BatchRetrieve(comb_index)
> ```
> 
> HTH.
> 
> Longer term I can see ways that we /could/ better support updatable indices within Terrier, but we dont have the bandwidth to address this.

Is it possible to save the `comb_index` to the hard drive? So that I can actually update an already existing index that I have?
