### ISSUE TITLE
IndexFactory error

### ISSUE THREAD

**Issue by stamatisvas** [terrier-org/pyterrier#33]
Hi. I am trying to load an index using:

indexref = /path/to/terrier/index/
index = pt.IndexFactory.of(indexref)

and I am getting the following error:
AttributeError: module 'pyterrier' has no attribute 'IndexFactory'

**Comment by cmacdonald** [comment]
You need pt.init() first.

As of today, you need to use the github version, following the Colab notebooks for the installation procedure (pip install git...) rather than pip install python-terrier

**Comment by cmacdonald** [comment]
Sorry, I needed my coffee this morning. It should be:
```
pt.IndexFactory.of(pt.IndexRef.of('/path/to/terrier/index/data.properties'))
```

**Comment by stamatisvas** [comment]
Ok thanks. So I used

index = pt.IndexFactory.of(pt.IndexRef.of('index/data.properties'))

the command executed but the index seems to be NoneType so when I try 

print(index.getCollectionStatistics().toString())

I am getting:

AttributeError                            Traceback (most recent call last)
<ipython-input-39-61959cc4da45> in <module>()
----> 1 print(index.getCollectionStatistics().toString())

AttributeError: 'NoneType' object has no attribute 'getCollectionStatistics'

Please note that the index created using the latest terrier-core.

**Comment by cmacdonald** [comment]
As per my edit above, if you have a relative path to your index, use './index/data.properties' as the location string.

If you have problems, you can set `pt.logging("INFO")` or `pt.logging("DEBUG")` to see more of the underlying problem at the Terrier end.

**Comment by stamatisvas** [comment]
Its working now. By mistake I missed the ./ before the index. Thanks a lot!

**Comment by cmacdonald** [comment]
I'll take on board that `pt.IndexFactory.of()` returning None is a silent error, and will leave this issue open. Needing the "./" is an underlying problem in Terrier that should be resolved as we slowly remove ApplicationSetup.

**Comment by cmacdonald** [comment]
This is now addressed upstream: https://github.com/terrier-org/terrier-core/issues/117
Thanks for your feedback @stamatisvas
