### ISSUE TITLE
Error While Importing Library

### ISSUE THREAD

**Issue by J9rryGou** [terrier-org/pyterrier#331]
![image](https://user-images.githubusercontent.com/106114570/195719896-b32e45b5-58a7-4af5-82f3-b351c383b4f8.png)

I confirm that the library is installed since you can view the package version as shown as below:
![image](https://user-images.githubusercontent.com/106114570/195720088-0dd1d03f-e764-443f-af43-8e770c626343.png)

The machine I am using is runing on Ubuntu 20.04.

**Comment by seanmacavaney** [comment]
Hey @J9rryGou,

Running `pt.init()` after `import pyterrier as pt` should do the trick.

This is necessary to give users the chance to make any changes to pyterrier's configuration.

 \- sean

**Comment by J9rryGou** [comment]
> Hey @J9rryGou,
> 
> Running `pt.init()` after `import pyterrier as pt` should do the trick.
> 
> This is necessary to give users the chance to make any changes to pyterrier's configuration.
> 
> - sean

Hi Sean,

Thank you for your reply! Did I miss something here?
![image](https://user-images.githubusercontent.com/106114570/195849620-6a91533e-330d-4822-b0d1-a8dc566f0d91.png)

Also, is it possible to let the package load compressed index from PISA? When you want to shoot a query into PISA, you need to provide:
Take CW09B as an example:
term lexicon: CW09B.fwd.termlex
document lexicon: CW09B.url.fwd.doclex
WAND data: CW09B.wand
compressed inverted index: CW09B.index.opt
compress method: block_simdbp

You know, CW09B is quite large. It is not reasonable to create the index in realtime. Can we use the library to read these stuff and play something with index? The function I want to use your library is also very basic:

For a given term _t_ and document _d_, I want to get the score of _t_ in _d_. Is it possible to do this? Basically, I want to do the index loading one time and do such lookup in realtime.

Thanks!

**Comment by cmacdonald** [comment]
You need to have Java of some form installed. I’ll let Sean reply about Pisa - we have a separate repo for pyt_pisa

**Comment by seanmacavaney** [comment]
Sure, you can convert individual PISA files into the format the pt_pisa expects. Since there are not "standard" names for each of the files in PISA, it may take a bit to match them up. But here's what pt_pisa expects to be in a directory:

```
fwd # not actually used, but if PISA adds support for PRF someday, it probably will be, so that's why we keep it around
fwd.doclex # binary document id file => CW09B.url.fwd.doclex?
fwd.documents # not actually used, plain text document id file for generating fwd.doclex
fwd.termlex # binary term file => CW09B.fwd.termlex?
fwd.terms # not actually used, plain text term file for generating fwd.termlex
fwd.urls # not actually used, but generated by PISA
inv.docs # non-compressed inverted docid file, needed to generated bmw and compressed index files
inv.freqs # non-compressed inverted frequency file, needed to generated bmw and compressed index files
inv.sizes # non-compressed inverted length file, needed to generated bmw and compressed index files
pt_pisa_config.json # see below
```

`pt_pisa_config.json` stores metadata about how the index was generated (e.g., what tokenizer), since this isn't otherwise stored in any file. This is important for the software to know how to process queries the same way. The file looks like this:

```
{"stemmer": "porter2", "index_encoding": "block_simdbp", "query_algorithm": "block_max_wand"}
```

Note that bmw data compressed indexes are dependent on the ranking model and their parameters. I recommend just letting pt_pisa just recreate them for you (it's not a super time-consuming process), but if you really want to skip the step, those files will look like:

```
bm25.k1-0.9.b-0.4.q0.bmw.1000 # => CW09B.wand? (Which retrieval function/parameters used to generate this?)
bm25.k1-0.9.b-0.4.q0.bmw.1000.block_simdbp # => CW09B.index.opt?
```

If you want to discuss bits of this further, it's probably best to create an issue in this repo: https://github.com/terrierteam/pyterrier_pisa

**Comment by J9rryGou** [comment]
> You need to have Java of some form installed. See https://pyterrier.readthedocs.io/en/latest/installation.html.
> 
> I’ll let Sean reply about Pisa - we have a separate repo for pyt_pisa

Thanks!

**Comment by J9rryGou** [comment]
> Sure, you can convert individual PISA files into the format the pt_pisa expects. Since there are not "standard" names for each of the files in PISA, it may take a bit to match them up. But here's what pt_pisa expects to be in a directory:
> 
> ```
> fwd # not actually used, but if PISA adds support for PRF someday, it probably will be, so that's why we keep it around
> fwd.doclex # binary document id file => CW09B.url.fwd.doclex?
> fwd.documents # not actually used, plain text document id file for generating fwd.doclex
> fwd.termlex # binary term file => CW09B.fwd.termlex?
> fwd.terms # not actually used, plain text term file for generating fwd.termlex
> fwd.urls # not actually used, but generated by PISA
> inv.docs # non-compressed inverted docid file, needed to generated bmw and compressed index files
> inv.freqs # non-compressed inverted frequency file, needed to generated bmw and compressed index files
> inv.sizes # non-compressed inverted length file, needed to generated bmw and compressed index files
> pt_pisa_config.json # see below
> ```
> 
> `pt_pisa_config.json` stores metadata about how the index was generated (e.g., what tokenizer), since this isn't otherwise stored in any file. This is important for the software to know how to process queries the same way. The file looks like this:
> 
> ```
> {"stemmer": "porter2", "index_encoding": "block_simdbp", "query_algorithm": "block_max_wand"}
> ```
> 
> Note that bmw data compressed indexes are dependent on the ranking model and their parameters. I recommend just letting pt_pisa just recreate them for you (it's not a super time-consuming process), but if you really want to skip the step, those files will look like:
> 
> ```
> bm25.k1-0.9.b-0.4.q0.bmw.1000 # => CW09B.wand? (Which retrieval function/parameters used to generate this?)
> bm25.k1-0.9.b-0.4.q0.bmw.1000.block_simdbp # => CW09B.index.opt?
> ```
> 
> If you want to discuss bits of this further, it's probably best to create an issue in this repo: https://github.com/terrierteam/pyterrier_pisa

Hi Sean,

Does this mean I should use the uncompressed index rather than the compressed index?
