### ISSUE TITLE
pt.init() doesn't work right

### ISSUE THREAD

**Issue by meepo9** [terrier-org/pyterrier#332]
This afternoon around 5, I ran my colab project as before, but an error jumped up when initializing pyterrier. 

I'm pretty sure it's an internal bug because I asked my classmates to run it in different projects and on different devices and it's still here.

It seems to be a syntax error in one of the library files. The screenshot looks like this. 

![Image](https://user-images.githubusercontent.com/116689651/197899448-ade01b39-24ca-401f-b87a-941d59eb0269.jpeg)

Please help me out, thanks.

**Comment by seanmacavaney** [comment]
This looks to be an issue with the `cwl_eval` package, which is used for measures like `RBP`.

Version 1.0.11 of `cwl_eval` just appeared on pypi with the above syntax error. You should be able to install the previous version (1.0.10) to resolve the issue:
```bash
pip install cwl-eval==1.0.10
```

Note that if you're using an interactive session (e.g., a notebook), you'll have to restart it after installing the `cwl-eval` to resolve the issue.

Does this work for you?

I posted an issue about this (https://github.com/ireval/cwl/issues/22) in `cwl_eval`.

**Comment by meepo9** [comment]
Dear Sean,

 

Yes, it works! Actually, I think somebody fixed it late last night. I didn’t change anything and it worked. Thank you anyway.

 

Best,

Meepo 😊

 

发件人: Sean MacAvaney ***@***.***> 
发送时间: 2022年10月26日 5:43
收件人: terrier-org/pyterrier ***@***.***>
抄送: meepo9 ***@***.***>; Mention ***@***.***>
主题: Re: [terrier-org/pyterrier] pt.init() doesn't work right (Issue #332)

 

The issue in cwl-eval is now fixed, so the latest version should resolve the issue. This means that installing pyterrier for the first time should now work (since it'll pull the latest cwl-eval), or upgrading cwl-eval as follows:

pip install --upgrade cwl-eval

Does it work for you now @meepo9 <https://github.com/meepo9> ?

**Comment by cmacdonald** [comment]
Great, thanks for the update!
