### ISSUE TITLE
MemoryIndexer not found on Windows

### ISSUE THREAD

**Issue by seanmacavaney** [terrier-org/pyterrier#347]
(Reporting a bug found on a student's machine.)

**Describe the bug**
Using the latest version of PyTerrier on Windows, you can get an error that says that the MemoryIndexer class in the helper jar isn't found. Curiously, it did have the "correct" version of the JAR installed under ~/.pyterrier (0.0.7), it just wasn't the actual 0.0.7 (since the MemoryIndexer wasn't included). Deleting the file simply re-downloaded the wrong version again.

I was able to resolve the issue by copying over a correct version of the file from a linux version (it was pointed instead to a file under the ~/.m2 directory).

**To Reproduce**
1. Which index
2. Which retrieval
3. What pipeline
4. What was the dataframe output
5. See error

**Expected behavior**

**Documentation and Issues**
 - [ ] I have checked the [PyTerrier documentation](https://pyterrier.readthedocs.io/en/latest/) for relevant content
 - [ ] I have checked for previous relevant [PyTerrier issues](https://github.com/terrier-org/pyterrier/issues)

**Screenshots**

**Additional context**

**Comment by cmacdonald** [comment]
Hmm, actually I think the problem is pyterrier 0.8 and more modern helpers...? Can they ensure to upgrade to pyterrier 0.9.1?

**Comment by seanmacavaney** [comment]
Yep, I'll check

**Comment by cmacdonald** [comment]
any update?

**Comment by seanmacavaney** [comment]
yeah, it was a version issue. Sorry!
