### ISSUE TITLE
Trying to get dataset 'irds:cord19/trec-covid' stuck at 0% and then times out

### ISSUE THREAD

**Issue by Trojan13** [terrier-org/pyterrier#356]
**Describe the bug**
When trying to get the dataset 'irds:cord19/trec-covid'  the download seems to start but is then stuck at 0%. After a while it times out.

**To Reproduce**
1. Import pyTerrier
2. Copy the codesnippet from the readme.md

```
dataset = pt.get_dataset('irds:cord19/trec-covid')
indexer = pt.IterDictIndexer('./cord19-index')
index_ref = indexer.index(dataset.get_corpus_iter(), fields=('title', 'abstract'))
```
4. Run the script
6. See error

**Expected behavior**
Start downloading the dataset.

**Documentation and Issues**
 - [x] I have checked the [PyTerrier documentation](https://pyterrier.readthedocs.io/en/latest/) for relevant content
 - [x] I have checked for previous relevant [PyTerrier issues](https://github.com/terrier-org/pyterrier/issues)

**Screenshots**
![image](https://user-images.githubusercontent.com/6168895/208236078-1a33a063-6012-458c-9d87-f613253918f2.png)

**Additional context**
I am mainly interested for the trec-covid dataset due to an university project but Ive tested some other datasets from the docs. Some work but some do not.  Small list ive tested:

Works:
irds:argsme/1.0
irds:argsme/2020-04-01/debatepedia
irds:kilt/codec/economics

Does not work:
irds:cord19/trec-covid
irds:cord19/trec-covid/round5
irds:beir/climate-fever
irds:beir/cqadupstack/gis
irds:beir/hotpotqa
irds:clinicaltrials/2021/trec-ct-2022

**Comment by Trojan13** [comment]
Okay nevermind. Ive ran it outside a notebook and now it is displaying to download progress. **The notebook output was just not displaying the progress.**

**Comment by cmacdonald** [comment]
Was this Colab or Jupyter?

**Comment by Trojan13** [comment]
I've tried it on both.
