### ISSUE TITLE
Cannot set term.max.length property

### ISSUE THREAD

**Issue by dburian** [terrier-org/pyterrier#357]
**Describe the bug**
I seem not to be able to set `term.max.length` property. After I run the code below an error is raised saying:

> ERROR org.terrier.structures.seralization.FixedSizeTextFactory - Term 12265Changed###PubDate:01-01-02;Zone:OC;Ed:1;Section:F;Page:F1;PubCha written in 70 bytes. Max expected size was 61. Increase relevant property: max.term.length for Lexicon, or indexer.meta.forward.keylens for metadata

yet I set the property to higher value.

**To Reproduce**
Unfortunately the data I work with are not open sources, so I cannot share them here. But the minimal setup would be something like this:

```python
pt.set_property("max.term.length", 80)
pt.set_property("indexer.meta.forward.keylens", 80)
index = pt.TRECCollectionIndexer(
    "./trec_index",
    threads=1,
    stemmer=pt.index.TerrierStemmer.none,
    stopwords=pt.index.TerrierStopwords.none,
    tokeniser=pt.index.TerrierTokeniser.whitespace,
    overwrite=True,
    properties={"max.term.length": 80, "indexer.meta.forward.keylens": 80},
)


index_ref = index.index(en_doc_paths[:1])
```

I am not sure where to set the above properties as I was unable to find it in the docs. So I just set it wherever I've seen properties set throughout the documentation and Github issues.

**Expected behavior**
An error should not be thrown or the error should have an updated value for `max.term.length` property.

**Documentation and Issues**
 - [x] I have checked the [PyTerrier documentation](https://pyterrier.readthedocs.io/en/latest/) for relevant content
 - [x] I have checked for previous relevant [PyTerrier issues](https://github.com/terrier-org/pyterrier/issues)

**Additional context**
I am new to Terrier and PyTerrier so I may be missing something obvious. However I am stuck on this for the last 4 hours.

**Comment by dburian** [comment]
So after some work I found out what was the issue. I think it boils down to silenced errors on the java's side of things for setting a property to an integer. Basically:

- `pt.set_property("some.property", 42)` will get ignored, while 
- `pt.set_property("some.property", "42")` works.

The following snippet is the minimal reproducible code:
```python
import pyterrier as pt

if not pt.started():
  pt.init()

print("Before:")
print(pt.properties["max.term.length"] if "max.term.length" in pt.properties else "none") # none
print(pt.ApplicationSetup.appProperties.getProperty("max.term.length", "none")) # none

pt.set_property("max.term.length", 40)

print("After setting an int:")
print(pt.properties["max.term.length"]) # 40
print(pt.ApplicationSetup.appProperties.getProperty("max.term.length", "none")) # none

pt.set_property("max.term.length", "40")

print("After setting a string:")
print(pt.properties["max.term.length"]) # 40
print(pt.ApplicationSetup.appProperties.getProperty("max.term.length", "none")) # 40
```
 
I am not so familiar with Java, though I could have guessed `Properties` stores only strings. Indeed call to `pt.ApplicationSetup.appProperties.setProperty("some.property", 42)` raises an error.

#### What to change

- have `pt.set_property` to shout at you if you didn't give it two strings (key and value). 
- emphasize in the documentation property values **must** be strings.

I am leaving this open, since I think at least one of the changes above should be implemented.

**Comment by cmacdonald** [comment]
Thanks @dburian. Good spot, I'll give a look at what's going on here.

**Comment by dburian** [comment]
Not sure why I thought it is only **part** of the problem. Now setting `max.term.length` with `pt.set_property` and string value does fix the problem for me.

So, feel free to close the issue once you feel all is done here :).
Thanks for your work, after couple of hours of work with PyTerrier I really do enjoy working with it :).
