### ISSUE TITLE
Create a custom model

### ISSUE THREAD

**Issue by noem-1998** [terrier-org/pyterrier#363]
Hello,
I'm new to this framework, i would like to know if there is already a feature that allows users to create and train their own rankers such as DPR and ANCE, ....
 
Thanks!

**Comment by cmacdonald** [comment]
We tend to keep dense stuff in different packages - they all interplay with PyTerrier, but arent part of the core platform.

Our recommendation when starting new on single-representation dense retrieval is https://github.com/terrierteam/pyterrier_dr

Craig

**Comment by noem-1998** [comment]
Thank you. this helps a lot.

Is there a way to save the trained model like a checkpoint?

**Comment by cmacdonald** [comment]
I'd suggest posting issues on the github tracker for that repo. I suspect that the model checkpoints can be saved like any other PyTorch model.
