### ISSUE TITLE
evaluate using pytrec_eval is slow

### ISSUE THREAD

**Issue by cmacdonald** [terrier-org/pyterrier#37]

**Comment by cmacdonald** [comment]
Mostly is about converting qrels and results to dictionaries; I have sped up pt.Experiment() by reusing the qrels dictionary. We cannot improve until https://github.com/cvangysel/pytrec_eval/issues/22 is fixed.

**Comment by seanmacavaney** [comment]
#48 should help with this in the meantime.

**Comment by cmacdonald** [comment]
Closing, as #48 and #50 address most of the issues. Thanks @seanmacavaney
