### ISSUE TITLE
Customize the BM25 score function 

### ISSUE THREAD

**Issue by oussaidene** [terrier-org/pyterrier#374]
Hi,

I'm wondering if there is a way to customize the BM25 score function? based on what i read IDF is computed by IDF = log((N - n + 0.5) / (n + 0.5)). This results in a negative value for terms appearing in more than half of the corpus documents. I wish to use : IDF = log((N - n + 0.5) / (n + 0.5) + 1), so that all scores are positives.

Thank you for any help!

**Comment by cmacdonald** [comment]
Yes! See https://pyterrier.readthedocs.io/en/latest/terrier-retrieval.html#custom-weighting-models

Test them on a smaller corpus first. Its slow, but allows you try out models without recompiling a new Java class.

**Comment by oussaidene** [comment]
Okay, thank you!
