### ISSUE TITLE
Richsoggang

### ISSUE THREAD

**Issue by 36bsog** [terrier-org/pyterrier#378]
**Describe the bug**

**To Reproduce**
1. Which index
2. Which retrieval
3. What pipeline
4. What was the dataframe output
5. See error

**Expected behavior**

**Documentation and Issues**
 - [ ] I have checked the [PyTerrier documentation](https://pyterrier.readthedocs.io/en/latest/) for relevant content
 - [ ] I have checked for previous relevant [PyTerrier issues](https://github.com/terrier-org/pyterrier/issues)

**Screenshots**

**Additional context**

**Comment by cmacdonald** [comment]
seemingly spam.
