### ISSUE TITLE
pyterrier downloads terrier-assemblies although it's found in `$CLASSPATH`

### ISSUE THREAD

**Issue by MangoIV** [terrier-org/pyterrier#389]
**Describe the bug**
pyterrier downloads terrier-assemblies although it's found in `$CLASSPATH`

```
ω ι $env.CLASSPATH
/nix/store/6in9y8nkbz6jlqi0gfrawbr54mngf6hh-terrier-assemblies-5.7/share/java/terrier-assemblies-5.7.jar:/nix/store/6in9y8nkbz6jlqi0gfrawbr54mngf6hh-terrier-assemblies-5.7/share/java/terrier-assemblies-5.7.jar
```

```sh
python3 pyterrier-test.py
terrier-assemblies 5.7 jar-with-dependencies not found, downloading to /home/mangoiv/Uni/ir...
 25% [.................                                                     ]  26050560 / 103899610^CTraceback (most recent call last):
```

```python
import pyterrier as pt
if not pt.started():
  pt.init()
     
vaswani = pt.datasets.get_dataset("vaswani")

TF_IDF = pt.BatchRetrieve(vaswani.get_index(), wmodel="TF_IDF")
BM25 = pt.BatchRetrieve(vaswani.get_index(), wmodel="BM25")
PL2 = pt.BatchRetrieve(vaswani.get_index(), wmodel="PL2")

pt.Experiment(
    [TF_IDF,BM25,PL2],
    vaswani.get_topics(),
    vaswani.get_qrels(),
    ['map','ndcg'])
```

**To Reproduce**
pyterrier version is latest release, for a reproducer refer to the file 

**Expected behavior**
jar from classpath is used 

**Documentation and Issues**
 - [x] I have checked the [PyTerrier documentation](https://pyterrier.readthedocs.io/en/latest/) for relevant content
 - [x] I have checked for previous relevant [PyTerrier issues](https://github.com/terrier-org/pyterrier/issues)

**Screenshots**

**Additional context**

**Comment by cmacdonald** [comment]
I dont think Python can search the Java classpath, as the Java classpath isnt known until Java starts. Hence, I'd rather keep the current functionality. You can symlink the jar file you have into $HOME/.pyterrier/ folder.
