### ISSUE TITLE
How do I use a downloaded index on another device

### ISSUE THREAD

**Issue by AbdulmueezEmiola** [terrier-org/pyterrier#391]
Hello, 
I created my pyterrier index on a server. Due to some cost concerns. I do not have access to the server again. I downloaded the index folder and I'm currently trying to query the index locally but I get an error.
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jnius\jnius_export_class.pxi", line 1164, in jnius.JavaMultipleMethod.__call__
  File "jnius\jnius_export_class.pxi", line 877, in jnius.JavaMethod.__call__
  File "jnius\jnius_export_class.pxi", line 1043, in jnius.JavaMethod.call_staticmethod
  File "jnius\jnius_utils.pxi", line 79, in jnius.check_exception
jnius.JavaException: JVM exception occurred: Could not load an index for ref ./index/data.properties, even though IndexLoader org.terrier.structures.IndexOnDisk$DiskIndexLoader could support that type of index. It may be your ref had a wrong location; Terrier logs may have more information. java.lang.IllegalArgumentException`
Can someone help with pointers on how to fix this issue?

**Comment by seanmacavaney** [comment]
Hi,

So to clarify, you've copied an index directory from one machine to another, and now get this error? Are you using BatchRetrieve?

**Comment by cmacdonald** [comment]
Can you specify the full path to the index. This is simple a file not found type of error.

Craig
________________________________

**Comment by AbdulmueezEmiola** [comment]
Hello, Thank you for your help.
I switched to using absolute paths and It works well now.
Another question I have is, Can I host the index on an s3 bucket and use?

**Comment by cmacdonald** [comment]
I'm not too familiar with S3. Can you mount it as a file system in the local machine?

Terrier has a filesystem abstraction layer that could work, but its not something I'd recommend we look into unless there is no other solution.

Craig
