### ISSUE TITLE
Clarify in documentation how to change stop words and stemming configuration at indexing and retrieval

### ISSUE THREAD

**Issue by KexinYue** [terrier-org/pyterrier#40]
Could you supplement some information about how to removing stop words and stemming in the "index_api.ipynb" tutorial?

**Comment by cmacdonald** [comment]
At indexing time:
```
indexer = TRECCollectionIndexer()
indexer.setProperties(**{"termpipelines" : ""})
```

At retrieval time:
```
br = BatchRetrieve(index, properties={"termpipelines" : ""})
```

Properties are global, so try not to mix different retrieval settings using different termpipelines, as there can be unintended consequences. We will adjust this in the future, see https://github.com/terrier-org/terrier-core/issues/122

I will give a look at how the documentation can be improved.

**Comment by cmacdonald** [comment]
Now fixed, thanks @KexinYue
