### ISSUE TITLE
Metrics are all zero with webis-touche2020 dataset

### ISSUE THREAD

**Issue by Jia-py** [terrier-org/pyterrier#409]
**Describe the bug**
```python
pt.init(version=5.7, helper_version="0.0.7")
dataset = pt.get_dataset('irds:beir/webis-touche2020/v2')
retriever = pt.BatchRetrieve(index, wmodel='BM25', metadata=['docno','text'])
```
all the metrics are zero using bm25 in webis-touche2020 dataset, the same code works good for other datasets, such as beir/TREC-COVID.

**To Reproduce**
1. Which index - irds:beir/webis-touche2020/v2
2. Which retrieval - bm25 with default parameters
3. What pipeline - just bm25 retriver
4. What was the dataframe output - it has the retrieved results, but with all metrics zero.

**Comment by Jia-py** [comment]
<img width="1104" alt="image" src="https://github.com/terrier-org/pyterrier/assets/58099973/840a1584-82b0-4107-acca-38de6a498d94">

**Comment by seanmacavaney** [comment]
Hi @Jia-py -- thanks for reporting.

Terrier indexes have a maximum length for the fields that they store, which includes the `docno`. The default of 20 is often enough, but some datasets (such as touche) have longer docnos.

To change the maximum length, you'll need to set `meta={"docno": 39}` (the maximum docno is 39 characters in the dataset), as follows:

```python
indexer = pt.IterDictIndexer('./indices/beir_webis-touche2020_v2', meta={"docno": 39})
```

I hope this helps!

**Comment by Jia-py** [comment]
Hi @seanmacavaney, thanks for your time and help! It works well now.

**Comment by seanmacavaney** [comment]
No problem, happy to help :)
