### ISSUE TITLE
Bug found in the a value error raise

### ISSUE THREAD

**Issue by freemikka** [terrier-org/pyterrier#422]
**Describe the bug**
In line 303 of io.py SUPPORTED_RESULTS_FORMATS should be SUPPORTED_TOPICS_FORMATS

**Expected behavior**
Expected the dict SUPPORTED_TOPICS_FORMATS, got the the dict SUPPORTED_RESULTS_FORMATS 

**Documentation and Issues**
 - [yes] I have checked the [PyTerrier documentation](https://pyterrier.readthedocs.io/en/latest/) for relevant content
 - [no] I have checked for previous relevant [PyTerrier issues](https://github.com/terrier-org/pyterrier/issues)

**Comment by cmacdonald** [comment]
Thanks for the report @freemikka. Bug now fixed in master branch.
