### ISSUE TITLE
JavaException: JVM exception occurred: org/terrier/structures/indexing/DocumentPostingList java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by lovelyyeswanth** [terrier-org/pyterrier#424]
Hi @cmacdonald 

While I was trying to create an index using IterDictIndexer, I received NoClassDefFoundError error.

This is the snippet I used with Python 3.9.12 and python-terrier 0.10.0.

I was tried to run this code

def iter_file(filename):
    with open(filename, 'rt') as file:
        for l in tqdm(file):
            # yields a dictionary for each json line
            doc = json.loads(l)
            yield {'docno' : doc["id"], 'text' : doc["text"]}
        file.close()

gc.collect()
index_dir = ds_dir + "index_full/"

if not os.path.exists(index_dir+"data.properties"):
    index_full_ref = pt.IterDictIndexer(index_dir).index(iter_file(ds_dir+"collection.jsonl"), 
                                                    meta = ('docno', 'text'), fields = ('text',))
else:
    print("Index already created!")
    index_full_ref = pt.IndexRef.of(index_dir+"data.properties")

gc.collect()

got the error,

AttributeError: module 'pyterrier' has no attribute 'IterDictIndexer'

So I have included the line of code

from pyterrier.index import IterDictIndexer

then got the error

---------------------------------------------------------------------------
JavaException                             Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 from pyterrier.index import IterDictIndexer

File ~\anaconda3\lib\site-packages\pyterrier\index.py:1265, in <module>
   1262         lastdoc = self.collection.getDocument()
   1263         return lastdoc
-> 1265 class DocListIterator(PythonJavaClass):
   1266     dpl_class = autoclass("org.terrier.structures.indexing.DocumentPostingList")
   1267     tuple_class = autoclass("org.terrier.structures.collections.MapEntry")

File ~\anaconda3\lib\site-packages\pyterrier\index.py:1266, in DocListIterator()
   1265 class DocListIterator(PythonJavaClass):
-> 1266     dpl_class = autoclass("org.terrier.structures.indexing.DocumentPostingList")
   1267     tuple_class = autoclass("org.terrier.structures.collections.MapEntry")
   1268     __javainterfaces__ = [
   1269         'java/util/Iterator',
   1270     ]

File ~\anaconda3\lib\site-packages\jnius\reflect.py:209, in autoclass(clsname, include_protected, include_private)
    206 cls_start_packagename = '.'.join(clsname.split('.')[:-1])
    208 # c = Class.forName(clsname)
--> 209 c = find_javaclass(clsname)
    210 if c is None:
    211     raise Exception('Java class {0} not found'.format(c))

File jnius\\jnius_export_func.pxi:22, in jnius.find_javaclass()

File jnius\\jnius_utils.pxi:79, in jnius.check_exception()

JavaException: JVM exception occurred: org/terrier/structures/indexing/DocumentPostingList java.lang.NoClassDefFoundError

Can u help me rectify this error

I appreciate your help in fixing this issue.

Regards,
yeswanth

**Comment by cmacdonald** [comment]
Did you run pt.init() ?

**Comment by lovelyyeswanth** [comment]
I have uninstalled python-terrier and reinstalled now it is working, i have seen this in one of your comments
