### ISSUE TITLE
get_corpus_iter() from a Terrier index

### ISSUE THREAD

**Issue by cmacdonald** [terrier-org/pyterrier#425]
pyterrier_pisa has a get_corpus_iter(), courtesy of @seanmacavaney 

It would be useful to have such a function for a Terrier index.

A few options that I can foresee:

1.  Terrier's Index class can expose a single get_corpus_iter() method that has pretokenized option. 
If pretokenized is true a version of the direct index.
If pretokenized is false, its a version of the meta index.

2. Expose these in the relevant classes:
a. direct index exposes a get_corpus_iter() which is pretokenized
b. meta index exposes  a get_corpus_iter() which is metadata

3. Both!

**Comment by cmacdonald** [comment]
So option 3?

**Comment by seanmacavaney** [comment]
I'd like the default to be to return everything that's available. If there's a case where that isn't needed, we can add options later.

**Comment by cmacdonald** [comment]
#430 merged
