### ISSUE TITLE
typo at docs

### ISSUE THREAD

**Issue by wpertsch** [terrier-org/pyterrier#463]
There is a Typo at https://pyterrier.readthedocs.io/en/latest/io.html
I think "singleline" is missing a L.

Is this the right way to report a typo in the docs?
kind regards!

**Comment by cmacdonald** [comment]
Thanks for the report. 
If you navigate to https://github.com/terrier-org/pyterrier/blob/master/pyterrier/io.py#L293 and press Edit, i think github takes you through the process of making a Pull Request

**Comment by cmacdonald** [comment]
Now fixed, thanks for the report
