### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by soldni** [terrier-org/pyterrier#54]
Hello!

Thank you for creating this project; it looks very promising, and I would like to use it in my own research. To enable me to do so, could you please add a license to the package? The [Mozilla Public License](https://github.com/terrier-org/terrier-core/blob/5.x/LICENSE.txt) used in Terrier would be a great candidate. 

Thank you,

Luca

**Comment by cmacdonald** [comment]
Hi Luca,

Thanks for your positive comments and the note about the license. I will confirm this and update this thread.

Craig

**Comment by cmacdonald** [comment]
I confirm, the license will be MPL (like Terrier), I will tag other contributors here to see if they object? @seanmacavaney @tonellotto ?

**Comment by tonellotto** [comment]
Fine for me!

**Comment by cmacdonald** [comment]
Hi Luca, I have addressed. Thank you!

**Comment by soldni** [comment]
Excellent, thank you very much Craig!

-Luca
