### ISSUE TITLE
Set operators should not suppress other columns

### ISSUE THREAD

**Issue by cmacdonald** [terrier-org/pyterrier#56]
Set-Intersect and Set-Union drop all columns except, qid, query and docno. This is wrong. It should keep other attributes around.

Report by @Xiao0728

**Comment by albertoueda** [comment]
Got it, sorry, but actually that was the requested behavior on https://github.com/terrier-org/pyterrier/pull/51 .

**Comment by cmacdonald** [comment]
IMHO, set operators should only suppress rank and score, as the output is a set, and therefore cannot be ordered.

**Comment by cmacdonald** [comment]
Without this patch, we cannot do:
```python
(
  BatchRetrieve(index, wmodel="A", metadata=["docno", "body"] 
  | BatchRetrieve(index, wmodel="A", metadata=["docno", "body"] 
) >> BERT()
```
which is a central use case for the operators.

**Comment by albertoueda** [comment]
> IMHO, set operators should only suppress rank and score, as the output is a set, and therefore cannot be ordered.
I agree, I was definetely not sure about suppressing all the other columns at that time. Good point!

**Comment by cmacdonald** [comment]
> Actually, I still think the score columns should be renamed, not suppressed.

I dont want to proliferate columns unnecessarily. Somebody that needs them can join themselves.

I think @Xiao0728 has this working so going to close.
