### ISSUE TITLE
Setting parameters for BM25 model and apply query expansion

### ISSUE THREAD

**Issue by yasumori** [terrier-org/pyterrier#59]
I could not find anywhere in the documentation, but it would be helpful to know how to set parameters for the BM25 model.
I'm assuming that the parameters for the Terrier document are also applied to Pyterrier BM25: http://terrier.org/docs/v4.0/javadoc/org/terrier/matching/models/BM25.html

Is there any way to change these parameters from Pyterrier? Perhaps, should I modify something in the controls of the BatchRetrieve class?

**Comment by cmacdonald** [comment]
Hi, 
its a little convoluted, but here is an example:

```
pt.BatchRetrieve(index, wmodel="BM25", controls={"c":"0.15"}, properties={"bm25.k_1": "0.2"})
```

Making this more uniform means changes in Terrier, but I have it in mind.

**Comment by yasumori** [comment]
Hi Craig, 

Thanks for your quick reply. 

Could I also ask if there is any way to apply query expansion using Pyterrier?

**Comment by cmacdonald** [comment]
Two ways:

```
pt.BatchRetrieve( controls={"qe":"on"} )
```
OR
```
pt.BatchRetrieve( ) >> pt.rewrite.Bo1QueryExpansion(index) >> pt.BatchRetrieve( ) 
```

**Comment by yasumori** [comment]
Thanks a lot for your help. Closing the issue.

**Comment by cmacdonald** [comment]
So there are a few examples in pipeline_experiments.md. So that we can improve the documentation. where would you have expected to see these?

**Comment by yasumori** [comment]
Thanks for pointing me to pipeline_experiments.md.
In general, I think it would be helpful to know how minor parameter settings could be done in PyTerrier.
For example, it took me a while to realise that there's a parameter `indexer.meta.forward.keylens` needs to be changed to have a longer `doctag`.

Would it be possible to translate the "Common Configuration Options" section of Java Terrier documentation into Pyterrier?
https://github.com/terrier-org/terrier-core/blob/5.x/doc/index.md?

**Comment by cmacdonald** [comment]
In general, I'm trying to expose all Terrier configuration more easily in Pyterrier, i.e. I would like to remove the indexing properties!
________________________________

**Comment by yasumori** [comment]
That sounds like good improvement of accessibility to PyTerrier.
Thank you for creating this software first of all.

**Comment by yasumori** [comment]
Just an additional question.
I this a correct way to change the "b" parameter? 
`properties={'bm25.b': '0.0'}`
I changed "b" from 0.0 to 1.0 with 0.1 interval using the above definition, but results were not changed at all.

**Comment by cmacdonald** [comment]
controls={"c" : "0.1"}

I have a student working on a grid-search tool, it will be integrated at some point in next month or so, with examples.

Craig
________________________________

**Comment by yasumori** [comment]
Hi Craig,

Thanks for your help. The grid-search sounds helpful to find good parameter settings.
Would it be possible to let the system produce an error message when an invalid parameter is set?

Yasu

**Comment by cmacdonald** [comment]
I dont /think/ so, just because of the way that Terrier's config works. But we can keep this in mind.

**Comment by yasumori** [comment]
Okay I understand that.
