### ISSUE TITLE
How does BatchRetrieval.transform handle string in other language or special character

### ISSUE THREAD

**Issue by S1E9** [terrier-org/pyterrier#62]
Cases like 
retr = pt.BatchRetrieve(index, controls = {"wmodel": "TF_IDF"}).transform("TF_IDF") or 
retr = pt.BatchRetrieve(index, controls = {"wmodel": "TF_IDF"}).transform("órgãos")
will cause
JVM exception occurred: Failed to process 'órgãos' org.terrier.querying.parser.QueryParserException

**Comment by cmacdonald** [comment]
Hi @S1E9,
Thanks for your report. I verified this with:
```
from jnius import JavaException
try:
   br("órgãos")
except JavaException as ja:
   print(ja.stacktrace)
```
which gave me:
``` 
["org.terrier.querying.parser.QueryParserException: Failed to process 'órgãos'", 'org.terrier.querying.parser.QueryParser.parseQuery(QueryParser.java:68)', 'org.terrier.querying.parser.QueryParser.parseQuery(QueryParser.java:50)', 'org.terrier.querying.TerrierQLParser.process(TerrierQLParser.java:39)', 'org.terrier.querying.LocalManager.runSearchRequest(LocalManager.java:916)', 'Caused by:', 'org.terrier.querying.parser.TokenMgrError: Lexical error at line 1, column 1.  Encountered: "\\u00f3" (243), after : ""', 'org.terrier.querying.parser.TerrierQLParserTokenManager.getNextToken(TerrierQLParserTokenManager.java:409)', 'org.terrier.querying.parser.TerrierQLParser.jj_scan_token(TerrierQLParser.java:969)', 'org.terrier.querying.parser.TerrierQLParser.jj_3R_5(TerrierQLParser.java:664)', 'org.terrier.querying.parser.TerrierQLParser.jj_3_1(TerrierQLParser.java:761)', 'org.terrier.querying.parser.TerrierQLParser.jj_2_1(TerrierQLParser.java:296)', 'org.terrier.querying.parser.TerrierQLParser.parseOne(TerrierQLParser.java:50)', 'org.terrier.querying.parser.TerrierQLParser.parse(TerrierQLParser.java:75)', 'org.terrier.querying.parser.QueryParser.parseQuery(QueryParser.java:64)', 'org.terrier.querying.parser.QueryParser.parseQuery(QueryParser.java:50)', 'org.terrier.querying.TerrierQLParser.process(TerrierQLParser.java:39)', 'org.terrier.querying.LocalManager.runSearchRequest(LocalManager.java:916)']
```

This is an upstream Terrier regression - we changed the query parser a while back. I'll make a Terrier issue.

**Comment by cmacdonald** [comment]
i have fixed this - see terrier-org/terrier-core#131

I have validated it with:
```python
import pyterrier as pt
pt.init()
indexref = pt.datasets.get_dataset("vaswani").get_index()
br = pt.BatchRetrieve(indexref, wmodel="BM25")
br("órgãos")
```

Until terrier-core 5.4 is released, you will need to install the github version of terrier-core to your local Maven repo. On Google Colab, the following incantation is sufficient to achieve this:
```
!apt-get install maven
!git clone https://github.com/terrier-org/terrier-core.git && cd terrier-core && mvn -DskipTests clean install
```

**Comment by S1E9** [comment]
Thanks so much for the solution. But I encountered with another similar problem which occurs when I tried to use "children's literature" as a query string. It gives me the same JVM exception.

**Comment by cmacdonald** [comment]
Remove the ‘

Ideally use pt.io.read_topics() which will tokenise the topics first.

Craig

Sent from my iPhone

On 6 Sep 2020, at 09:08, Eric <notifications@github.com> wrote:

﻿

Thanks so much for the solution. But I encountered with another similar problem which occurs when I tried to use "children's literature" as a query string. It gives me the same JVM exception.

**Comment by valentin-fngr** [comment]
Hi,  
Do you have any idea why I have this error ? 
`jnius.JavaException: JVM exception occurred: Failed to process qid 1 'How can you make a friend?' -- Lexical error at line 1, column 27.  Encountered: <EOF> after : "" org.terrier.querying.parser.QueryParserException`

after doing bm25.search(d) ? 
When I do bm25.search("hello"), it works well !

**Comment by cmacdonald** [comment]
Remove the ? and ' from the query

**Comment by valentin-fngr** [comment]
Yep, it works. 
I used : 

`query = "".join([x if x.isalnum() else " " for x in query])`

Thank you for your help
