### ISSUE TITLE
How to represent n-gram in the query

### ISSUE THREAD

**Issue by ponshane** [terrier-org/pyterrier#63]
The transform function of BatchRetrieve's instance accepts the query, which is formulated as words splited by space such as "word1 word2 word3 ...".  I just wonder is there any way to represent n-gram? For example, I hope to retrieve documents with _"high temperature"_ rather than those with either _"high"_ or _"temperature"_.

Thanks for answering.

**Comment by cmacdonald** [comment]
Hi @ponshane 

If you have an index with blocks (aka positions), then querying with phrases should work as expected.

Moreover, you can use the `#1` or `#owN` operators from Indri with Terrier. See https://github.com/terrier-org/terrier-core/blob/5.x/doc/querylanguage.md#matching-op-query-language

Craig

**Comment by ponshane** [comment]
Hi @cmacdonald 

Thanks for your help and information. After reindexing with blocks, I successfully retrieve documents by querying phrases.

Shane
