### ISSUE TITLE
stemming is configured as default setting when using query expansion

### ISSUE THREAD

**Issue by Xiao0728** [terrier-org/pyterrier#70]
When conducting bo1 query expansion on the unstemmed index, the expanded terms are stemmed.
When inspect `pt.rewrite.ApplyTermPipeline_default.getInfo()`, it returns used porter stemmer.

**Comment by cmacdonald** [comment]
Fixed, such that QueryExpansion will pick up what terrier.properties are set when its constructed. Not ideal, but in line with the other Terrier-based transformers.
