### ISSUE TITLE
query and document apply functions

### ISSUE THREAD

**Issue by cmacdonald** [terrier-org/pyterrier#73]
Make it easier to make a lambda transformer for common use cases:
 - document scoring, based on rows
 - query rewriting, based on rows

The two transformer classes are:
```python
class LambdaDocumentScoringTransformer(TransformerBase):
    """
        Scores each document in a dataframe by using a specified function, which can be a lambda. Updates rank column.
    """
    def __init__(self, lambdaFn,  *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fn = lambdaFn
    
    def transform(self, inputRes):
        fn = self.fn
        outputRes = inputRes.copy()
        outputRes["score"] = outputRes.apply(fn, axis=1)
        outputRes = add_ranks(outputRes)
        return outputRes

class LambdaQueryTransformer(TransformerBase):
    """
        Rewrites each query in a dataframe by using a specified function, which can be a lambda. 
    """
    def __init__(self, lambdaFn,  *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fn = lambdaFn

    def transform(self, inputRes):
        fn = self.fn
        outputRes = inputRes.copy()
        outputRes["query"] = outputRes.apply(fn, axis=1)
        return outputRes
```

NB: These differ from pt.LambdaTransformer, which applies on the entire dataframe at once.

**Comment by cmacdonald** [comment]
Proposed integration:
```python
doclen = pt.lambda.doc_score(lambda row: len(row.content)

stops = set(["in", "and"])
remove_stops = pt.lambda.query(lambda row: ' '.join([qt for qt in row["query".split(" ") if not qt in stops]))

```

**Comment by cmacdonald** [comment]
or:
```
doclen = pt.lambda("score", lambda row: len(row.content))

stops = set(["in", "and"])
remove_stops = pt.lambda("query", lambda row: ' '.join([qt for qt in row["query"].split(" ") if not qt in stops]))
```
?

**Comment by cmacdonald** [comment]
These are several types of transformation:

| Input | Output | Cardinality | Example    | Example lambda     | Input type               | Return type |
| ----- | ------- | ------- | -----------|----------------------- |-----------|-----------|
|    Q   |    Q        | 1 to 1  |Query rewriting | `pt.lambda.query() ` | row of one query  | str |
| QxD     | QxD   | 1 to 1    | Re-ranking   | `pt.lambda.doc_score() ` | row of one document | float |
| QxD     | QxDf   | 1 to 1    | Feature scoring   | `pt.lambda.feature_score() ` | row of one document | numpy array |
| QxD |    Q       | N to 1 | Query expansion |  |
| Q     | QxD       | 1 to N | Retrieval   | |

**Comment by albertoueda** [comment]
> or:
> 
> ```
> doclen = pt.lambda("score", lambda row: len(row.content))
> 
> stops = set(["in", "and"])
> remove_stops = pt.lambda("query", lambda row: ' '.join([qt for qt in row["query"].split(" ") if not qt in stops]))
> ```

I like this option more. Actually, I think we can assume that who's writing a lambda function knows her data (i.e., for me looks an advanced feature). In this sense, I think we could even abstract from the "column name" we are modifying: if it is the "score", "query", or anything else: the important information is the axis (rows or columns).

For instance, something like:
```python
outputRes[target_col] = outputRes.apply(fn, axis=1)
```

, letting the user specify what is intended to modify (even adding a new column if desired) and how. The query and doc modifiers (with add_ranks) would be particular cases of it.

**Comment by cmacdonald** [comment]
The latter you can already do easily, as it stands:
```
def _my_new_col_fn(res):
  res[target_col] = res.apply(fn, axis=1)
  return res

pipe = pt.BatchRetrieve() >> _my_new_col_fn
```

The purpose of this proposal is to add a bit more scaffolding - in particular, the semantics are a bit different depending on the transformation type:
 - for query rewriting, I plan to keep the original query around, so it can be restored
 - for re-ranking, the "rank" column needs to be recomputed.

So I actively want the user to decide which type of transformation they are making.

**Comment by cmacdonald** [comment]
Two comments:

1. @albertoueda suggested `pt.lambdas` as name was confusing, as nothing that was being done is actually a lambda, its just that it some functions can be expressed using lambdas.

Alternatively, @tonellotto described what is being performed might be described as an apply (Pandas nomenclature) or a map operation. The former is preferred, i.e. a PyTerrier module called `apply` having the methods described above.
 * `pt.apply.doc_score()`
 * `pt.apply.query()`

Alternatively, it could be `pt.applies`. But singular seems probably more natural.

2. We should have an apply operation that uses the current LambdaPipeline. This would allow more generic transformations, as in the bottom half of the table above.  We need a name for this function. Using the `_my_new_col_fn()` example above, here are some suggestions: 
 * `pyterrier.apply.dataframe(_my_new_col_fn)`
 * `pyterrier.apply.on(_my_new_col_fn)`
 * `pyterrier.apply.generic(_my_new_col_fn)`

So, e.g. the pipeline defined in the previous comment would be more clearly defined as:
```
pipe = pt.BatchRetrieve() >> pt.apply.generic(_my_new_col_fn)
```

**Comment by albertoueda** [comment]
The `apply` name is great!

On the generic apply, couldn't be simple as in other dataframe manipulation libs, like `apply(_my_new_col_fn)`? Not sure if it is possible if we have a module `apply` though.

```python
>>> np.apply_along_axis(my_func, 0, a)
```
or
```python
>>> df.apply(np.sum, axis=0)
```

Ref:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.apply.html
https://numpy.org/doc/stable/reference/generated/numpy.apply_along_axis.html

TBH, in case we need a name I like more something like `pyterrier.apply.my_function(fn)`.

**Comment by cmacdonald** [comment]
PR #80 has addressed this.
Documentation is available at https://pyterrier.readthedocs.io/en/latest/modules/apply.html

Thanks for all your comments @albertoueda and @tonellotto. 
New comments/issues/PRs gladly received for further improvements!
