### ISSUE TITLE
Make it easier to construct Q, D, R dataframes

### ISSUE THREAD

**Issue by cmacdonald** [terrier-org/pyterrier#78]
Suggestion by Jimmy Lin.

Currently, constructing an example topics dataframe (for testing) is done as follows:

```python
import pandas as pd
queries = pd.DataFrame([["q1", "query 1"], ["q2", "query 2"]], columns=["qid", "query"])
```

Examples:
```python
ex1 = pt.new_queries(["q1", "q2"], ["query 1", "query 2"])
ex2 = pt.new_queries(["query 1", "query 2"], qid=["q1", "q2"])
```

Decisions are:
 - the name of the helper function(s)
 - the parameters of the helper function(s) that can be easily remembered

**Comment by cmacdonald** [comment]
It could be within a module, e.g.`pt.new.queries()` ?

**Comment by albertoueda** [comment]
Actually, we did not have to assume Pandas: in the future, other dataframes/representations may be used, so the syntax could be independent from the dataframe library. We also could make use of **kwargs to add custom columns to returned object.

```python
// module "new"
def queries(queries, qids=None, **kwargs):
    if qids is None:
        qids = ["q1", "q2", ..., "qn"]

    // assert all values have same size
    ...

pt.new_queries(["query 1", "query 2"], query_types=["query 1 type", "query 2 type"])
```

**Comment by cmacdonald** [comment]
Sure, the function should be independent of the actual implementation. But it seems there is agreement on `pt.new.queries()`.

**Comment by cmacdonald** [comment]
@albertoueda work in progress branch: https://github.com/terrier-org/pyterrier/compare/pt_new?expand=1
Should the name be `pt.new.query()` or `pt.new.queries()`? (or both)? The current method can handle one of more queries.

**Comment by cmacdonald** [comment]
Now merged. Thanks for input @albertoueda
