### ISSUE TITLE
integer underflow on high frequency terms

### ISSUE THREAD

**Issue by seanmacavaney** [terrier-org/pyterrier#79]
(Not sure if this is the right place to post this issue, but I found it when working with pyterrier.)

I noticed when using the Index API, terms with very high frequencies may be prone to underflow errors:

```python
import pyterrier as pt
if not pt.started():
  pt.init()
JIR = pt.autoclass('org.terrier.querying.IndexRef')
indexref = JIR.of('./ClueWeb12-terrier/data.properties')
index = pt.IndexFactory.of(indexref)
lexicon = index.getLexicon()
lexicon['0'].frequency # -1963449987
lexicon['0'].documentFrequency # 522231036
```

(I got a warning that it `is a Terrier 4.2 index - temporarily upgrading.`, which may contribute to the issue?)

The frequency of `-1963449987` suggests an underflow. Since the java data type is a 32-bit signed int and the DF is 1/4 the max int size, this seems probable.

If the frequency remains less than 2x the maximum integer size, it's possible to recover the actual value in python like this:

```python
cf = lexicon['0'].frequency # -1963449987
if cf < 0:
    b = cf.to_bytes(4, byteorder='big', signed=True) # b'\x8a\xf8!}'
    cf = int.from_bytes(b, byteorder='big', signed=False) # 2331517309
```

Does this seem like a reasonable workaround?

**Comment by cmacdonald** [comment]
The workaround seems reasonable.
Indeed Terrier does this internally, see https://github.com/terrier-org/terrier-core/blob/61a8de6585031fa4915a7811d32cdbda0c021f71/modules/core/src/main/java/org/terrier/matching/models/WeightingModel.java#L114

How big is your index? It's fairly rare to see this, ie > CW09B.

**Comment by seanmacavaney** [comment]
Yeah, this is on the full ClueWeb12, so much larger than CW09b.

The approach you link to seems much more straightforward-- and ~20x faster based on my quick benchmark.

Thanks!
