### ISSUE TITLE
Add TREC WT10G topics & qrels as datasets

### ISSUE THREAD

**Issue by cmacdonald** [terrier-org/pyterrier#86]
Suggestion by @Xiao0728

**Comment by Xiao0728** [comment]
Yes, and please also include the DOTGOV topics & qrels as datasets.

**Comment by cmacdonald** [comment]
DOTGOV2 is covered by the "trec-terabyte" dataset.
DOTGOV is covered by trec-wt-2002, trec-wt-2003, trec-wt-2004

**Comment by cmacdonald** [comment]
Resolved
