### ISSUE TITLE
Precision Metrics

### ISSUE THREAD

**Issue by Xiao0728** [terrier-org/pyterrier#89]
Hi,
in pt.experiment, when using `eval_metrics=["map",  "ndcg", "ndcg_cut_20", "P" ]`  to report the evaluations, the "precision metric would be ignored. But report just with P, it works.

Xiao

**Comment by cmacdonald** [comment]
Indeed, it only seems to work when `baseline=0` is set?

**Comment by Xiao0728** [comment]
Yes, the same issue happens for "recall" metrics.

**Comment by cmacdonald** [comment]
Resolved. Also now require pytrec_eval 0.5
