### ISSUE TITLE
retrieving for a candidate set of documents

### ISSUE THREAD

**Issue by cmacdonald** [terrier-org/pyterrier#9]
@daltonj suggested being able to predetermine the candidate set of documents for retrieval.

Lets assume just using an API that inputs and outputs Pandas dataframes. 
Normal retrieval:
```
topics = df.DataFrame([["1", "test query"]], columns=["qid", "query"])
output = BatchRetrieve(index).transform(topics)
#output is like:
df.DataFrame([["1", "doc5", 5.3]], columns=["qid", "docno", "score"])
```

1. One option is to accept a reformulated dataframe:
```
input = df.DataFrame([["1", "test query", "doc5"], ["1", "test query", "doc4"] ], columns=["qid", "query", "docno"])
output = BatchRetrieve(index).transform(topics)
#output is like:
df.DataFrame([["1", "doc5", 5.3],["1", "doc4", 4.9]], columns=["qid", "docno", "score"])
```
We can think of this like the cartesian product of the topics and a resultset.
In this format, the query is repeated for every document, but thats not a huge overhead. 

BatchRetrieve would detect a "docno" or "docid" column in the input. 

2. Take the candidate set as a second dataframe
```
topics = df.DataFrame([["1", "test query"]], columns=["qid", "query"])
candidates = df.DataFrame([["1", "doc5"], ["1", "doc4"]], columns=["qid", "docno"])
output = BatchRetrieve(index).transform(topics, candidates)
#output is like:
df.DataFrame([["1", "doc5", 5.3]], columns=["qid", "docno", "score"])
```

BatchRetrieve would detect a candidates parameter to the method, and change configuration appropriately.  Again docno vs docid would change the Terrier configuration whether docno -> docid mapping was required.

**Composition**
It would be good to compose BatchRetrieves in a sequence:
```
firstpass = BatchRetrieve(index, "PL2")
rerank = BatchRetrieve(index, "PL2F")
ComposePipeline(firstpass, rerank)
```
I prefer option 1, but I'm not sure which option is more amenable to composition.  Would the ComposePipeline be responsible for guaranteeing that it joins the topics DF back to the results DF? Another option is to set a flag on the each component to tell it to return the topics too (or even do that by default??).

Perhaps each component could have an (optional) attribute that says the format of the response for each component? We can use that to check at construction time if the output of the component is correct. (A bit like a shape attribute in Numpy/Torch, which is used to ensure that the next component can be applied to the output of the previous one).

**Comment by daltonj** [comment]
This is why it's a bit awkward to do this in batch mode; these operations are not really batch.  It's really query-by-query.  A more natural interface would be:
docs = Retrieve(index).transform(topic) 
# turn docs into a set - do other operations, pooling methods, etc... 
Retrieve(index).transform(topic, docset)

For the batch retrieval, I think repeating the query text is a bit clunky.  It would be cleaner to just have two columns - the qid, docid and pass that into it.

**Comment by cmacdonald** [comment]
We discussed a solution where topics would be the equi-join of topics and documents, e.g.
```python
pd.DataFrame([["1", "where is ...", "doc1", 5 ]], columns=["qid", "query", "docno", "score"])
  qid         query docno  score
0   1  where is ...  doc1      5
```
the query would could be NaN, to avoid taking too much space.
```python
 pd.DataFrame([["1", "where is ...", "doc1", 5 ], ["1", None, "doc4", 4.9]], columns=["qid", "query", "docno", "score"])
  qid         query docno  score
0   1  where is ...  doc1    5.0
1   1          None  doc4    4.9
```

However, I'm starting to think that transform() should take, and return separate queries and documents dataframes:

```python
topics, _ = RewriteSDM(topics)
topics, docs = Retrieve().transform(topics)
topics, docs = Rerank().transform(topics, docs)
```

**Comment by cmacdonald** [comment]
This is well defined as:
```python
# rerank
topics_and_docs = Retrieve().transform(topics_and_docs)
```
with no plan to change currently.
